### ISSUE TITLE
Library fails to authenticate after some time

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1002]
We've got a number of Office 365 users that have reported that they're able to login and sync just fine initially. Then after a while, the sync stops working. Inspecting their logs presented this:

```
didFailWithError Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: efba60ac-f3ff-415f-b822-a07ee9bf6501
Correlation ID: bb6d2c17-63ab-453f-8334-e57c34d3dd4b
Timestamp: 2020-07-15 18:25:53Z, MSALOAuthErrorKey=invalid_client, MSALCorrelationIDKey=BB6D2C17-63AB-453F-8334-E57C34D3DD4B, MSALInternalErrorCodeKey=-42003}
```

Not sure what we need to do at our end? We're using the latest version of MSAL.

**Comment by jasoncoolmax** [comment]
@guidedways I have taken a look at the server logs, the error happens when MSAL sends a refersh token to server. Seems it is because device authentication is required by server while the macOS machine is not MDMed.

However, you mention the app could work fine initially but not some time later. I am wondering what scopes your app is trying to access. It will be helpful If you could provide me the full MSAL logs. Then I will take another look.

Thank you!

**Comment by jasoncoolmax** [comment]
Hi @guidedways, after second look, we find that the reason you got the error is because server thought your application was a confidential client. To get away from the issue, you might want to flip the following switch to YES (locate it by going to Azure Portal -> go to your registered application -> go to Authentication):

<img width="704" alt="Screen Shot 2020-07-30 at 12 14 17 PM" src="https://user-images.githubusercontent.com/8347347/88964535-5e5af700-d25e-11ea-8cff-9448c4c6bef7.png">

Meanwhile, we will consider improving by sending redirect uri to server in some of our flows, such that server will not mark your app as confidential client even you don't flip the switch above. An feature github issue has been created [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1020).

**Comment by guidedways** [comment]
@jasoncoolmax Thanks for this - no luck. The custom reported that they required authentication again even after we made the change. This is what the user shared with us:

```
MSAL authorization error, interactive required: Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALOAuthSubErrorKey=message_only, MSALCorrelationIDKey=4AEB477F-B83C-46E8-BFC7-19DAD5A5F0FF, NSUnderlyingError=0x60000cea6010 {Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.
Trace ID: f067c70d-2fcb-491d-b3f4-4cd94ac07100
Correlation ID: 4aeb477f-b83c-46e8-bfc7-19dad5a5f0ff
Timestamp: 2020-08-16 19:02:46Z, MSALOAuthErrorKey=invalid_grant, MSALOAuthSubErrorKey=message_only, MSALCorrelationIDKey=4AEB477F-B83C-46E8-BFC7-19DAD5A5F0FF, MSALInternalErrorCodeKey=-42004}}}
```
