### ISSUE TITLE
MSALWebviewParameters: windowed parentViewController not required, despite thrown error?

### ISSUE THREAD

**Issue by wvezey** [AzureAD/microsoft-authentication-library-for-objc#1041]
MSAL 1.1.7
iOS 13+
Xcode 11.6
Sim iPhone XR (13.4)

Using https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc as a reference, we are developing a POC for Azure App Proxy for our existing internal iOS app. Currently we use an OAuth2 authentication flow with our SSO server. Rather than execute the authentication flow from a view controller, we have abstracted all things authentication to a set of utility classes that checks and fetches tokens (both access token and refresh token, as needed) from the keychain, and does pretty much what the MSAL wrappers are doing, without the AD check; just pure SSO. Because a request for data is made as a part of app bootstrap, there is no view controller with a window (parentViewController.view.window == nil) at the time the first authentication check and request. Thus endeth the preamble.

When configuring the MSAL instance, you create an MSALWebviewParameters instance, sending a windowed view controller as the sole required argument. If the view controller does not have an associated window, an error is thrown from MSIDInteractiveRequestParameters+MSALRequest.m, in the code block lns 44-64. And I understand that this requirement is made in keeping with Apple documentation. If, however, you edit the source code slightly, and force this view controller check block to return YES, the authentication flow proceeds normally. I am speculating here, but it looks like AuthenticationServices::ASWebAuthenticationSession gets along just fine on its own steam.

I tried being a little goofy by generating a dummy window and view controller to satisfy the requirement, but for reasons that mystify me (because digging into the source code, while often a refreshing pastime, does tend to chew into available time), that did not work. So here's my request: rather than force us to change our app architecture to accommodate what looks like an unnecessary requirement, and here let me pause and state unequivocally that I could be, and often am, deeply wrong despite the certainty with which I express myself, please remove this requirement from the webview parameters setup.

Of course, I could be missing the point entirely, and the solution is staring me in the face while I stare back with the eyes of a dullard. It happens all the time.

**Comment by oldalton** [comment]
Thanks for looking into this. ASWebAuthenticationSession does require a windowed controller because we need to provide a valid window to this required callback: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/350409ef9ae2563652cd5faad0168a60c388c78a/IdentityCore/src/webview/systemWebview/session/MSIDASWebAuthenticationSessionHandler.m#L139

Depending on your modifications, MSAL might still be working because of this fallback logic we have: https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/350409ef9ae2563652cd5faad0168a60c388c78a/IdentityCore/src/util/ios/UIApplication%2BMSIDExtensions.m#L30

However, the fallback logic is unreliable if you have an iPad app with multiple windows. In order to make MSAL reliable, we require developer to be explicit about the controller and window they want to use for authentication. Please let us know if you have ideas for how to handle it better given that Apple is requiring us to provide a window.

**Comment by wvezey** [comment]
Olga, thank you for your thorough reply. I will probably just draw a crayon window and fax it into the app. This approach has worked well in the past. It sure beats writing code.

Closing this issue.
