### ISSUE TITLE
Xcode 12 issue navigator warnings

### ISSUE THREAD

**Issue by arangato** [AzureAD/microsoft-authentication-library-for-objc#1073]
XCode 12 shows "Validate project settings" warning in issue navigator and suggests a number of projects settings updates. See below the list of suggestions by Xcode 12.0 beta 6 (12A8189n).
Through some trial and error I discovered that turning on "swift whole module optimization" and "missing localizability static analysis" is enough to make Xcode happy (see checked ones on the screenshot).
Although there are several good suggestions on the list, my main issue is with issue navigator warning, as it clutters the view and makes real issues easier to miss.

![image](https://user-images.githubusercontent.com/49146595/91698050-c6ad3900-eb7a-11ea-8da3-c7009e4f2ef7.png)

**Comment by hieunguyenmsft** [comment]
Thank you for reporting this. Xcode 12 is still beta so we will wait until it's final.

**Comment by alobaili** [comment]
Xcode 12 is now released to the Mac App Store. I installed it and performed all the recommended changes given to me.

One particular change was upgrading the iOS deployment target to 12.0. After that, a bunch of new Buildtime warnings appear that some methods are deprecated since iOS 11.0 and 12.0.

![Screen Shot 2020-09-21 at 13 07 45](https://user-images.githubusercontent.com/27203112/93755150-7b32fb80-fc0b-11ea-9d47-e0efa4666108.png)

Can you kindly fix them?

Thank you all for the effort!

**Comment by ameyapat** [comment]
@arangato @alobaili Thanks for bringing this to notice. We have plans to resolve any deprecated methods and fix any issues related to xcode 12 and ios 14 soon.
