### ISSUE TITLE
Opening URL in intune SDK protected app

### ISSUE THREAD

**Issue by ShilpaGavade** [AzureAD/microsoft-authentication-library-for-objc#1122]
We are having an iOS and android application protected by Intune SDK and using MSAL auth library for login but we are using third party API's in it. These API's need cookies for authentication. We are capturing cookies using custom code and edge browser, which is managed browser in android but in iOS, not able to capture cookies using edge browser as it is going out of application so, is there any configuration from intune or azure side to open link in WKWebview (in iOS)?, not getting much information about it, is there any configuration needs to do from app side to protect app from data leak if we use WKWebView? We are stuck with this issue since long.
Any help would be appreciable.

**Comment by oldalton** [comment]
@ShruthiAchutha, is this something we support?

**Comment by ShruthiAchutha** [comment]
Can you clarify the scenario with maybe some screenshots/ video/ steps of what you are currently seeing and what you'd like to accomplish? In case you are asking if its okay to open third party websites within the app in a secure manner, then yes, you could use WKWebView but set that to unmanaged context so managed data doesn't leak into the web-view.

**Comment by ShilpaGavade** [comment]
hey @ShruthiAchutha, thank you for the reply, we are trying to capture cookies on login on third party portal.
so here are steps:
1) user is login with MSAL
2) After MSAL login, user is login again on third party portal, 
In case of android, user need not to login again as link is opening on edge browser and edge browser is a managed browser which already has been logged in with user.
3) In case of iOS, we are opening this third party login url on wkwebview, so, we are able to capture some required cookies.
As you mentioned set unmanaged context to web view, so what configuration does it require from intune side?
I mean, as  we know, we can set policies from azure portal to open link in edge or managed browser only, like wise, can we set policy for any specific url to open it on WKWebview?
Or do we need to do some configuration changes from our local application code?

Please let me know, if you need any other details.

**Comment by ShilpaGavade** [comment]
Just to add in it, 
currently we have set managed browser policy flag 'OFF' for opening link on edge browser, due to that we are able to open link on wkwebview but we can not set this flag always be 'OFF', because of which we are asking for settings or configurations from any side.

**Comment by ShilpaGavade** [comment]
@ShruthiAchutha , can we get any help regarding this?

**Comment by darosal** [comment]
@ShilpaGavade, setting the webview into an unmanaged context wouldn't be done through the Intune admin portal. This would be done programmatically. The managed browser policy affects outgoing URLs opened with `UIApplication`'s `openURL`, not web content that stays locally within the app through webviews. 

Shruthi was suggesting that before presenting the webview, the app should switch to an unmanaged context. Doing so will prevent managed data found within the app from leaking to a website in the webview should a user navigate through any links presented in it. After the webview is dimissed, the app should switch back to the managed context so that data within the app is not compromised.

Switching between unmanaged and managed contexts can be handled by setting the current UI policy identity. Setting this identity as a managed user will put the app in a managed context. Setting it to an empty string will put the app in an unmanaged context. This can be done using the `IntuneMAMPolicyManager`'s `setUIPolicyIdentity:...` methods

Before presenting the webview for third party auth, take note of the current identity and set the UI policy identity to an empty string. After dismissing the webview, be sure the set the UI policy identity back to the identity noted earlier.

**Comment by ShilpaGavade** [comment]
@darosal, one more thing related to this.. as we are opening link in unmanaged context, so, whatever we are capturing and storing locally is protected by intune?? As we know that intune protects organisation data in application (using 'Encrypt org data'), so captured cookies will be protected by intune or no?

**Comment by ShilpaGavade** [comment]
@darosal, referring to below url:
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios

which flag need to set, 'isExternalURL' or 'setUIPolicyIdentity'? 
Our third party website is corporate website only, which we are using for authentication purpose

**Comment by darosal** [comment]
@ShilpaGavade, the SDK mainly protects data by preventing it from leaving certain boundaries within the app. The 'Encrypt org data' policy enforces iOS encryption flags on data stored locally. Could you elaborate on how these cookies are captured? It's possible that we are defaulting to iOS protections for this. Data can also be protected using some of our public facing APIs found in `IntuneMAMDataProtectionManager.h` and `IntuneMAMFileProtectionManager.h`.

The `setUIPolicyIdentity` method would be the best option for it now.

**Comment by ShilpaGavade** [comment]
hello @darosal, thank you for your reply, can you please give more info regarding IntuneMAMDataProtectionManager, I mean, how can we utilise the functions from it?
And we are opening third party url using WKWebview inside the iOS application and capturing cookies through WKWebview, so, I am just checking if we are opening something in WKWebview then would it be protected by intune.

**Comment by darosal** [comment]
@ShilpaGavade, sure! Generally, these functions are used on data that a user might be able to manipulate. An example would be an app that handles files. All these files would be encrypted using the IntuneMAMFileProtectionManager and held in that state when at rest. The app only calls the unencrypt functions when the managed user attempts to open the file. If the unecrypt fails because the user isn't the owner or wasn't the managed account to encrypt the file in the first place, then the app prompts the user with an error message detailing why. It's also important to encrypt the file when the app is saving data to a location accessible outside the app. This way, only the unmanaged users don't read the data.

Could you explain more of a potential use case? I don't necessarily see the need for encrypting the captured cookies. If they are being stored in the keychain and not readable by users, there isn't really a concern of the data being leaked by the user.

Could you also explain more about what opening something in the webview means? Is the webview being used to access account documents that need to be protected? 

Here's an explanation of the functions in the IntuneMAMFileProtectionManager/IntuneMAMDataProtectionManager. The encrypt/protect functions within IntuneMAMFileProtectionManager/IntuneMAMDataProtectManager are called with the identity of the managed account. Calling them will return an encrypted/protected version of the data. Then when unencrypting or unprotecting the data, the SDK will use the current enrolled account as the identity. If the identities match, then the unencrypting/unprotecting will be successful and the original data will be returned

**Comment by ShilpaGavade** [comment]
Thanks @ShruthiAchutha  and @darosal for addressing issues. Let me explain complete flow for better understanding.

We are having an iOS and android application protected by Intune SDK and using MSAL auth library for authentication purpose. Android application working as expected but on iOS we are facing lots of issues related to intune, intune conditional access policy and MSAL authentication.

1) First thing, when our app starts it invokes Azure login page for authentication purpose, which is nothing but "login.microsftonline.com" and this authentication part is handled by MSAL library.
But from azure/intune portal side there is one conditional access policy is applied which is 
`Restrict web content transfer with other apps: Microsft Edge`
and also we are not using BYOD device registration, using MAM, I am not very clear about these terms but whatever I know I am trying to explain it.
so, this intune policy says that open web page only on managed browser, which is Edge but MSAL library on iOS open Safari by default so intune is giving error while authenticating, error is:
**You can't get there from here**
This is first issue we are facing in iOS, if this policy flag is disabled then we can authenticate successfully.

2) Second thing is after successful authentication on azure side, we are opening WKWebview inside application, which  opens third party url. We need to authenticate again on this third party url, after successful authentication, we are capturing some cookies. We need these cookies for further data fetching within application.
In android, this third party url is directly open on edge browser and we capture cookies from there but in iOS this is not possible as we can not capture cookies using edge due to iOS restriction.
so, my second question was that, as we are capturing these cookies and storing it locally in the app and using it to get data from API's. Is this cookies data protected by Intune?
And before opening WKWebview, do we need to set some flags like, 
``isExternalURL` or policyIdentity`, not sure, which one we need to use?

If you need any other details from my side then please let me know.

**Comment by darosal** [comment]
@ShilpaGavade I apologize for the delay. It might be best to schedule a call, if possible, to better answer any questions and track down the issues. Could you send an email to Shiv Patel at shpate@microsoft.com so that he can set that up? Thanks!

**Comment by ShilpaGavade** [comment]
@darosal : thank you for your response, will send an email to set up a call.
