### ISSUE TITLE
Error "The operation couldn't be completed. (MSALErrorDomain error ~50000.)" 

### ISSUE THREAD

**Issue by thomas-topway-it** [AzureAD/microsoft-authentication-library-for-objc#1266]
Hello, I get the following error on sign-in

```The operation couldn't be completed. (MSALErrorDomain error ~50000.) ```

just on ios (and using this library https://pub.dev/packages/msal_mobile )
while android works fine. Any idea how to solve that ? (I have followed all the steps related to the ios set-up) but I'm not sure where the error lies.
thanks
(Thomas)

**Comment by kaisong1990** [comment]
Thanks for your question.

There could be multiple causes for this. However without more logs, we cannot tell the root cause.

**Please note:** the library you provided is not officially published by us and please reach out to the original owner for further questions

**Comment by thomas-topway-it** [comment]
@kaisong1990 
I have no extra log currently. I could try to retrieve more information but I would need to know more about the multiple causes mentioned by you.

Regarding the external label, I have opened the issue in the original library as well
https://github.com/gbwisx/msal_mobile/issues/14
however it's not seem to be frequently maintained
(Thomas)

**Comment by bjoshua89** [comment]
@kaisong1990 I am also experiencing the same error. Below are the error codes.

- Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_request 
- MSALErrorDescriptionKey=AADB2C90288: UserJourney with id 'ResourceOwnerPasswordCredentials-RedeemRefreshToken' referenced in TechnicalProfile 'JwtIssuer' for refresh token redemption

Because of the error is am not able to get a new accessToken when the existing access token expires (using acquireTokenSilent) . I am using the 'MSAL' library using for IOS and Android.

Is there any way to get the acquireTokenSilent to get a new accessToken when the existing token expires.

**Comment by thomas-topway-it** [comment]
(*** attention, I will quote some commands in the external library, but I think they can be explanatory for msal as well)
It seems that using the following command to login
```
await msal.signIn(null, ['openid', 'Mail.Read', 'offline_access', 'email']).then((result) {
    //...
})
```
it does not work on ios (but it works on android). While using the following:

```
await msal.signIn(null, ["api://[app-registration-client-id]/[delegated-permission-name]"]).then((result) {
    //...
})
``` 
it works
(but I get the error
```You can't sign in here with a personal account. Use your work or school account instead.```

But the most important is that the webview opens on ios. Somebody has an explication why signing in with scopes does not work on ios but works on android ?
Thanks

**Comment by jasoncoolmax** [comment]
@thomas-topway-it I noticed that the library you are using hasn't been updated since 2019. So you are using a very old MSAL version. 
Could you use the latest MSAL to login? MSAL itself supports B2C natively. And you can see the sample app and guidance [here](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal).

**Comment by thomas-topway-it** [comment]
@jasoncoolmax 
thanks, it seems quite straightforward.
The only issue is that in our case it has to  be integrated in a flutter app,
so I have to check how it can be done.
Would be worth to publish an updated msal flutter library, given that the current library does not appear to be actively maintained ?
(Thomas)

**Comment by thomas-topway-it** [comment]
I think this issue can be closed because the following works

```
await msal.signIn(null, ["api://[app-registration-client-id]/[delegated-permission-name]"]).then((result) {
    //...
})
``` 

but another issue arises for which I have opened the following ticket

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1275

**Comment by thomas-topway-it** [comment]
@jasoncoolmax I have updated the msal version to the latest but the issue described in this thread, as well that here https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1275 is still there, do you have any hint why the code included https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1275  does not work ?
