### ISSUE TITLE
Brokered SSO with WKWebView and Intune

### ISSUE THREAD

**Issue by joeypatino** [AzureAD/microsoft-authentication-library-for-objc#1284]
Hi,

I’m attempting to configure an app with MSAL and Intune. After signing in using the Authenticator app I am redirected back to my app. I then attempt to show my secure website in a `WKWebView` but am asked to login again.

I’ve read this issue (https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1279) which is similar but doesn’t seem to provide an answer on how to resolve this or what another solution could be.

Here is how I am doing the MSAL & Intune login and registration process when no user is enrolled yet with Intune.

```
MSALWebviewParameters *webviewParams = [[MSALWebviewParameters alloc] initWithAuthPresentationViewController: viewController];
webviewParams.webviewType = MSALWebviewTypeWKWebView;

MSALInteractiveTokenParameters *parameters = [[MSALInteractiveTokenParameters alloc] initWithScopes:@[] webviewParameters:webviewParams];
[self.clientApplication acquireTokenWithParameters:parameters completionBlock:^(MSALResult* result, NSError *error) {
    // check error, etc...
    [IntuneMAMEnrollmentManager.instance registerAndEnrollAccount:result.account.username];
}];
```

**My question is:** 
Is it possible to enable SSO and then show secure content in a `WKWebView` in an iOS app using MSAL and Intune?

Thanks

---
**Test Info**
Device: iPhone Xs
OS: 14.4.2

MSAL 1.1.7
Intune 14.3.0

**Comment by NerevarineRule** [comment]
Hi joeypatino, for enabling SSO using MSAL, we recommend that you use ASWebAuthenticationSession.
Unfortunately, WKWebview doesn't share cookies or website data with other WKWebview instances, so SSO experience will be limited by this restriction. 

Please refer to this document - https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews

**Comment by joeypatino** [comment]
Hi @NerevarineRule, thanks a lot for the response. I understand the issue with cookie sharing in WKWebView and I'm fine with migrating the app to use SFSafariViewController instead

Would you be able to provide info on the correct URL to use when creating the `SFAuthenticationSession` instance? I can't seem to find an example anywhere showing what this should be for MSAL.

Regarding the Intune integration, after authenticating through the `SFAuthenticationSession` should I be able to simply call the `[IntuneMAMEnrollmentManager.instance loginAndEnrollAccount:nil];` (or ?) `[IntuneMAMEnrollmentManager.instance registerAndEnrollAccount:...];` method in order to load the app protection policies based on the previously cached token?

**Comment by NerevarineRule** [comment]
Hi @joeypatino. 

Could you please clarify which URL you are referring to? if you are referring to the redirect Uri, that's something you'd need to specify as a developer for your application as below:
```
MSALPublicClientApplicationConfig *pcaConfig = [[MSALPublicClientApplicationConfig alloc] initWithClientId:clientId
                                                                                                   redirectUri:redirectUri
                                                                                                     authority:authority];

MSALPublicClientApplication *application = [[MSALPublicClientApplication alloc] initWithConfiguration:pcaConfig
                                                                                                    error:&error];
```
                                                        


Also, SFAuthenticationSession is deprecated, and we'd recommend using ASWebAuthenticationSession instead.

Doing below should be enough. 
webViewParameters.webviewType  = MSIDWebviewTypeDefault

Lastly, could you please let me know where you came across those Intune related APIs? they don't look like APIs that we support on MSAL.

**Comment by joeypatino** [comment]
Hi @NerevarineRule, 

I was referring to the first parameter used in constructing the ASWebAuthenticationSession / SFAuthenticationSession class, the authentication URL. Am I misunderstanding things? It sounds like you're saying I don't need to create and manage a ASWebAuthenticationSession instance myself but should just be setting the `webviewType` property to `MSIDWebviewTypeDefault` when calling `acquireTokenWithParameters:`. 

The information on the Intune API's is found here: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios. The documentation does discuss that Intune should be compatible with MSAL (and previously with ADAL) but I haven't seen any code references on how to actually achieve this, and of course haven't been able to make this work yet.

----

I have migrated to using `SFSafariViewController` in the app and am setting the webViewType = MSIDWebviewTypeDefault. I have set the redirect URL when constructing the `MSALPublicClientApplication`. When I call `acquireTokenWithParameters:`, I am redirected to the MS Authenticator app where I can login or choose from an already logged in user and am then redirected back into my app. At this point I open my secure website, I am requested to login again. It seems that the cookies are not being shared still. 

Thanks for your feedback,

**Comment by joeypatino** [comment]
Hello, 

Also as additional info, after being redirected back into my application I am calling the InTune SDK (`registerAndEnrollAccount`) and am receiving back a MAM Policy, but I still am requested to login a second time in the in-app `SFSafariViewController`. The `registerAndEnrollAccount` step is described in the documentation I linked above regarding how to integrate MSAL and Intune.

Thanks,

**Comment by NerevarineRule** [comment]
Thanks @joeypatino. Sorry for the delay.

Just to double check did you make sure to override Intune APP SDK default values, as recommended in the document?
"If your app already uses MSAL to authenticate users, the app must use its existing registration values and override the Intune App SDK default values. This ensures that users are not prompted for authentication twice (once by the Intune App SDK and once by the app)."


If you have already done so and still get prompted for authentication twice, then could you please help to provide the following?

1) post your code snippet here -  Especially you mentioned "the first parameter used in constructing the ASWebAuthenticationSession". I am not clear on what you mean by that, so I think it would be best to get the code snippet on the following areas: 
i) how you are initializing MSAL & configuring webview 
ii)  acquiring token 
iii) and lastly, calling Intune SDK.

2) Also help to provide your MSAL log with level = MSALLogLevelVerbose? 
Here's an instruction on enabling MSAL logging: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc
I'd like to see logging from your app flow - from MSAL webview init -> token acquisition -> intune SDK invocation -> to see why you are requested to login a second time

**Comment by joeypatino** [comment]
Hi,

No problem on the delay! I really do appreciate the assistance

Re the Intune SDK value overrides: Yes, I believe I have these configured correctly. The only settings I've seen referenced for InTune have been the `IntuneMAMSettings` dictionary in the plist, specifically `ADALAuthority`, `ADALClientId`, and `ADALRedirectUri` and I have these set to the same values I use when creating the MSAL app instance. 

1. 
i) I believe I was misunderstanding how things were supposed to work. At first I thought I was supposed to create the `ASWebAuthenticationSession` instance myself. This was what I was referring to. I'm not doing this since it doesn't seem to be what is required. You can ignore this point.

ii) Here is how I setup the MSAL client application instance:
```
- (void)setupMSALClient {
    NSError *authoriyErr = NULL;
    NSString *endPoint = @"https://login.microsoftonline.com/TENENT_ID";
    MSALAuthority *authority = [MSALAuthority authorityWithURL:[NSURL URLWithString:endPoint] error:&authoriyErr];
    MSALPublicClientApplicationConfig *configuration = [[MSALPublicClientApplicationConfig alloc] initWithClientId:CLIENT_ID
                                                                                                       redirectUri:REDIRECT_URL
                                                                                                         authority:authority];

    MSALGlobalConfig.brokerAvailability = MSALBrokeredAvailabilityAuto;
    // for debugging
    MSALGlobalConfig.loggerConfig.logLevel = MSALLogLevelVerbose;
    [MSALGlobalConfig.loggerConfig setLogCallback:^(MSALLogLevel level, NSString *message, BOOL containsPII) {
        [Console.shared log:[NSString stringWithFormat:@"%@", message], nil];
    }];

    NSError *clientAppErr = NULL;
    self.clientApplication = [[MSALPublicClientApplication alloc] initWithConfiguration:configuration error:&clientAppErr];
    [self loadAccount];
}
```

Presenting the webview is done by simply creating the instance and presenting it:
```
- (void)presentWebview:(NSNotification *)notification {
    id<IntuneMAMAppConfig> config = [IntuneMAMAppConfigManager.instance appConfigForIdentity: IntuneMAMEnrollmentManager.instance.enrolledAccount];

    SFSafariViewController *viewController = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:config.fullData.firstObject[@"rooturl"]]];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:viewController];
    navigationController.modalPresentationStyle = UIModalPresentationFullScreen;
    [self presentViewController:navigationController animated:YES completion:nil];
}
```

ii) The Acquiring Token call is performed when the application resumes active. 
iii) The Intune registration call is performed after successfully acquiring a token.
```
- (void)resumeSession {
    if (self.isSigningIn) { return; }
    
    [self loadAccount];
    if (self.account) {
        MSALSilentTokenParameters *params = [[MSALSilentTokenParameters alloc] initWithScopes:@[] account:self.account];
        [self.clientApplication acquireTokenSilentWithParameters:params completionBlock:^(MSALResult* result, NSError *error) {
            if (result) {
                [[NSNotificationCenter defaultCenter] postNotificationName:@"presentWebview" object:nil];
            } else if (error) {
                [Console.shared log:[NSString stringWithFormat:@"Did fail Silently Acquiring Token: %@", error], nil];
            }
            self.isSigningIn = NO;
        }];
    } else {
        self.isSigningIn = YES;
        [[NSNotificationCenter defaultCenter] postNotificationName:@"presentInitializing" object:nil];
        
        MSALWebviewParameters *webviewParams = [[MSALWebviewParameters alloc] initWithAuthPresentationViewController: Console.shared.currentViewController];
        webviewParams.webviewType = MSALWebviewTypeDefault;

        MSALInteractiveTokenParameters *params = [[MSALInteractiveTokenParameters alloc] initWithScopes:@[] webviewParameters:webviewParams];
        [self.clientApplication acquireTokenWithParameters:params completionBlock:^(MSALResult* result, NSError *error) {
            if (result) {
                self.account = result.account;
                [IntuneMAMEnrollmentManager.instance registerAndEnrollAccount:result.account.username];
            } else if (error) {
                [Console.shared log:[NSString stringWithFormat:@"Did fail Acquiring Token: %@", error], nil];
            }
        }];
    }
}

- (void)loadAccount {
    NSArray<MSALAccount *> *accounts = [[self.clientApplication allAccounts:nil] filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(MSALAccount *acc, NSDictionary<NSString *, MSALAccount *> *bindings){
        return [acc.username isEqualToString:IntuneMAMEnrollmentManager.instance.enrolledAccount] || [acc.username isEqualToString:IntuneMAMEnrollmentManager.instance.mdmEnrolledAccount];
    }]];
    self.account = accounts.firstObject;
}

```

2) I've enabled verbose logs in the sdk. I performed a logout operation which appeared to have cleared the keychain and then deleted the app from the device before reinstalling and then capturing these logs, so they should represent a "clean" run. On opening the app I'm immediately redirected to the Authenticator app where I authenticate. The very last line of the logs is where the `SFSafariViewController` is presented and the URL that is loaded is our secure site, but of course that is never loaded and the user has to login again.
[logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6398290/logs.txt)

**Comment by NerevarineRule** [comment]
Hi Joey, Thanks for your quick response.

1)  I've noticed you are still using SFSafariViewController, which doesn't support SSO. you should use ASWebAuthenticationSession, not SafariViewController. You can see in below table for iOS 11+ SFSafariVeiwController doesn't share cookies. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-single-sign-on-sso-implications

2) Additionally, in the Intune App SDK document it also says "If for some reason your app must use a webview type other than WKWebView for any interactive MSAL auth operations, then it must also set SafariViewControllerBlockedOverride to true under the IntuneMAMSettings dictionary in the application's Info.plist. " So it might also be beneficial to change MAM settings while using ASWebAuthenticationSession. 
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal


Sorry I know it can be confusing, but SFSafariViewController is different from ASWebAuthenticationSession - here's an example of how one might use ASWebAuthenticationSession:
https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service?language=objc

**Comment by joeypatino** [comment]
Hi Peter, 

1) I've replaced the SFSafariViewController with a ASWebAuthenticationSession instance and this still does not work. The user is always required to login in the ASWebAuthenticationSession webview, even if they have already authenticated before using the MS Authenticator App, or by logging in using their username / password in the ASWebAuthenticationSession webview.

Additionally, and this could just be me misunderstanding the ASWebAuthenticationSession, but I never receive the closure callback for ASWebAuthenticationSession; except if the user selects "Cancel". 

Here is my code for creating the ASWebAuthenticationSession. Am I using the correct Url? This is actually the URL that I was referring to in my original follow up post. 

```
    // what is the correct URL here? 
    NSURL *url = [NSURL URLWithString:@"https://login.microsoftonline.com/common/oauth2?client_id=CLIENT_ID"];
    self.session = [[ASWebAuthenticationSession alloc] initWithURL:url
                                                 callbackURLScheme:@"CALLBACK_URI" completionHandler:^(NSURL *url, NSError *error) {
    }];
    if (@available(iOS 13.0, *)) {
        [self.session setPresentationContextProvider:self];
    }
```
- (void)presentWebview:(NSNotification *)notification {
    [self.session start];
}
```

2) Very good point here. It was required to set SafariViewControllerBlockedOverride to true. Not doing this prevented the login through the ASWebAuthSession and resulted in an error "You can't get there from here"

Thanks!

**Comment by NerevarineRule** [comment]
Hi @joeypatino. 
After further investigation, if you are using Intune MAM SDK, it allows SSO & single login on WKWebview as well.
This is likely due to not configuring Intune MAM SDK correctly in your code.
Could you please reach out to the Intune MAM SDK team in this repo? They might be able to help you with this better:

https://github.com/msintuneappsdk/ms-intune-app-sdk-ios

Thanks.

**Comment by joeypatino** [comment]
Hi Peter,
Alright. I will follow up with the Intune SDK team. 

Thanks,

**Comment by hieunguyenmsft** [comment]
As the issue is forwared to Intune team, I close this ticket here. Feel free to re-open it.

**Comment by Kyle-Reis** [comment]
Hey @NerevarineRule. This issue does not appear tp be an Intune-related issue. I think there may be some confusion about what the problem is here. There is no problem with single sign on between Intune and MSAL (as @joeypatino has confirmed that Intune silent enrollment works without issue after the app uses MSAL directly to to acquire a token). 

It sounds like the problem here is that once the application has initiated MSAL auth and the tokens have been stored in the keychain,. the expectation is that if the app navigates to a website within a webview which supports AAD accounts, the tokens acquired at the application level can be used to silently authenticate the user without prompting for credentials. Is this a supported scenario?

**Comment by joeypatino** [comment]
Hi @NerevarineRule , are you able to provide an answer on if this scenario is supported in the MSAL SDK?

**Comment by NerevarineRule** [comment]
@joeypatino
Yep, that should be the supported scenario. 
Just to confirm did you make sure that all your applications share the same client id and application id? on the iOS platform, tokens are stored in the keychain as kSecClassGenericPassword type object, and one of the primary identifiers is the client id, so just want to make sure, based on the document below: 


https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios

Silent SSO between apps
MSAL supports SSO sharing through iOS keychain access groups.

To enable SSO across your applications, you'll need to do the following steps, which are explained in more detail below:

Ensure that all your applications use the same Client ID or Application ID.
Ensure that all of your applications share the same signing certificate from Apple so that you can share keychains.
Request the same keychain entitlement for each of your applications.
Tell the MSAL SDKs about the shared keychain you want us to use if it's different from the default one.
Use the same Client ID and Application ID
For the Microsoft identity platform to know which applications can share tokens, those applications need to share the same Client ID or Application ID. This is the unique identifier that was provided to you when you registered your first application in the portal.

The way the Microsoft identity platform tells apps that use the same Application ID apart is by their Redirect URIs. Each application can have multiple Redirect URIs registered in the onboarding portal. Each app in your suite will have a different redirect URI. For example:

App1 Redirect URI: msauth.com.contoso.mytestapp1://auth
App2 Redirect URI: msauth.com.contoso.mytestapp2://auth
App3 Redirect URI: msauth.com.contoso.mytestapp3://auth

**Comment by joeypatino** [comment]
Hi @NerevarineRule, your response confuses me a little bit. I am not really using or attempting to share credentials between multiple apps. 

To be clear, I would like to initiate the MSAL auth (via the brokered SSO flow) in my app and would then like the tokens acquired to be used to silently authenticate the user (without prompting for credentials again) within a webview which supports AAD accounts. 

Did you mean that the website needs to be configured to somehow use the same client and application ID? If so, is this something done through the Azure portal or in the site itself? I unfortunately don't have access to the portal so I can't just check for these settings myself.

**Comment by NerevarineRule** [comment]
HI @joeypatino 

What I meant was that the credentials used during the stage when you initially used MAMSDK to acquire token, and then the credentials used subsequently by MSAL should be the same in order for MSAL to retrieve the correct token from the keychain token cache. 

Even within the same app, the credentials used to acquire token should remain consistent between MAMSDK and MSAL was what I meant. 

Based on the information provided so far, it is unclear to me which part of MSAL is giving you the issue with silent token acquisition.

How about this? would you mind sharing the entire source code in .tar format that contains all the instances where you are using MSAL and Intune MAM SDK?
I would like to cross-reference your code vs our sample code base and MSAL usage to see where it differs.

**Comment by Kyle-Reis** [comment]
Hey @NerevarineRule - as I mentioned before, single sign on between MSAL and Intune is actually working fine. There is no problem there. @joeypatino has confirmed that the app is able to acquire a token via MSAL with a credential prompt and then silently enroll in Intune and get policy with no additional prompt. The problem comes after all of this. 

After MSAL authentication and Intune enrollment, the app navigates to a website within a webview, and that site also authenticates with AAD. User gets prompted again for their credentials by the website. It sounds like the question here is whether it’s possible to share the app’s sign in state with this site so that the user doesn’t experience a 2nd prompt?

**Comment by NerevarineRule** [comment]
@Kyle-Reis, yep. I wasn't disputing that. 

Earlier in the thread, I did indicate that in order to share SSO states between MSAL and his secure website, he would need to use ASWebAuthenticationSession. (https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-single-sign-on-sso-implications)
It seemed like @joeypatino was having trouble with ASWebAuthenticationSession, so I provided additional information regarding what would be needed to enable silent SSO on our MSAL library to make sure his setup is correct.
Based on the code snippets provided, I am not able to draw conclusion, so I am requesting @joeypatino provide his full .m file so I can take a look into how he is using MSAL, particularly ASWebAuthenticationSession.

**Comment by Kyle-Reis** [comment]
@NerevarineRule - I see. From the Intune perspective, the recommendation is that applications [avoid using system web views](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#special-considerations-when-using-msal-for-app-initiated-authentication), because they run out-of-process and therefore the content they display cannot be managed.

@joeypatino - Once the app authenticates with the website in the webview, is it possible for org data to be displayed within the webview? If so, is it feasible for the app to directly access the same AAD resources as this site and display content in native UI rather than within a webview?

**Comment by Kyle-Reis** [comment]
I had another thought which might enable this scenario with fewer changes needed in the app:

@NerevarineRule - If initial MSAL authentication takes place within a WKWebView rather than kicking out to the Authenticator app, would the website be able to use the auth state if same WKWebView is used to navigate to it?

@joeypatino - Is there a hard requirement to support brokered authentication in the app? Or is this something you would be fine with disabling?

**Comment by joeypatino** [comment]
Hi @NerevarineRule, I can not share the exact source files but I will rewrite a sample with just the bare MSAL functionalities & webview and share this with you. I will post that this week.

@Kyle-Reis, No I unfortunately can not access the org's data outside of a webview, i.e. there is no API setup to access it. My client is requiring the brokered SSO flow.

**Comment by joeypatino** [comment]
Hi @NerevarineRule, sorry for the delay on this. I've put together an updated sample .h and .m that shows just my usage the MSAL and Intune SDK's. I've also included a couple other classes, one containing the `MSALPublicClientApplication`, and the other is just the AppDelegate to show the `openUrl` method handling, in case that's the culprit or I'm missing something there...

Using this setup, the application does open the MS Authenticator app, but after being redirected back to the app the user is still requested to login again within the `ASWebAuthenticationSession`. 

Thanks again for any feedback you can give on this. Let me know if I can provide any other files as well.

[msal-1284.tar.gz](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/6741039/msal-1284.tar.gz)

**Comment by NerevarineRule** [comment]
@joeypatino  - sorry for the delay, and thank you for sharing the source code.
Multiple things:

1) you don't have to create your own ASWebAuthenticationSession; once you set the webview type to default, MSAL takes care of that internally.  could you chance webviewParams.webviewType = MSIDWebviewTypeAuthenticationSession and see what happens?

2) In your app delegate, I see you created callback mechanism, but for iOS 13+ you need to add the callback in UISceneDelegate instead
https://swiftpack.co/package/AzureAD/microsoft-authentication-library-for-objc
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios#sso-through-authentication-broker-on-ios

```
- (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)URLContexts
 {
     UIOpenURLContext *context = URLContexts.anyObject;
     NSURL *url = context.URL;
     NSString *sourceApplication = context.options.sourceApplication;
     
     [MSALPublicClientApplication handleMSALResponse:url sourceApplication:sourceApplication];
 }
```

3) Let's do one more sanity check
In your MainViewController/authenticateWithMSAL 
Can we try to inspect MSAL result to see access token is retrieved silently?
```
    if (self.account) {
        MSALSilentTokenParameters *params = [[MSALSilentTokenParameters alloc] initWithScopes:@[] account:self.account];
        [[ClientApplication.shared clientApplication] acquireTokenSilentWithParameters:params completionBlock:^(MSALResult* result, NSError *error) {
            if (result) {
                //Peter: try to inspect result.accessToken here? 
                dispatch_async(dispatch_get_main_queue(), ^{ [self presentWebview]; });
            } else if (error) {
                NSLog(@"Did fail Silently Acquiring Token: %@", error);
            }
        }];
    } else {
```

4) Another sanity check - I initially believed your case fell under SSO Between MSAL and Safari, but since you are also involving the MS Authenticator - it doesn't hurt to double check scenario and see if you have all the configurations set up as per "SSO through Authenticator broker on iOS"
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-macos-ios#sso-through-authentication-broker-on-ios 

5) Lastly, since MSAL internally initializes ASWebAuthenticationSession and handles all the mechanism for you, 
when you specify aforementioned webview type, I think it would also be good to check how your UI application is handling browser opening in the Safari browser
https://stackoverflow.com/questions/57800669/reuse-access-token-from-msal-in-web-view

**Comment by joeypatino** [comment]
Hi @NerevarineRule, Sorry for my delay in responding. I've been away on vacation and haven't had time to get back to this until now.

1. Ok. I understand. I've removed the `ASWebAuthenticationSession` instance and changed the webviewType to `MSALWebviewTypeAuthenticationSession`; The behavior is the same though, a second login is required inside the webview( SFSafariViewController).

2. I'm not actually using Scenes in my project but to be thorough, I've added the SceneDelegate and implemented the required method

3. I logged the token after the silent authorization. The token is available. I inspected it using https://jwt.io/ and the claims appear present, though to be honest I'm not sure I would really know if any were missing or incorrect.

4. I have checked confirmed that the steps listed in **SSO through Authentication broker on iOS** are implemented.

5. I took a look at that SO link. Setting the application to open the Safari browser, instead of SFSafariViewController, still requires a second login inside the Safari.

If you have more ideas please let me know, I'm still hoping that there's a solution for this. 

Thanks

**Comment by eldimious** [comment]
Hey I am facing the same issue when we are using MDM devices + intunes, while seems in our local devices is working properly. In our current implementation we have a method called `loginUser` which makes the following steps: 

1. creates MSALPublicClientApplication
2. tries to find getCurrentAccount (getCurrentAccount(with: msalParameters, completionBlock: { currentAccount, _, error in)
3. If account exists calls acquireTokenSilent to get new token silently: (.acquireTokenSilent(with: parameters) { result, error in)
4. If account == nil call acquireToken to re-login employee

btw we have set webViewParamaters.webviewType = .authenticationSession 

While in our local devices the above flow seems is working and when we run it on managed devices, every time it re-asks the user to relogin.

Any thoughts or workarround?

**Comment by NerevarineRule** [comment]
@joeypatino 
interesting.. is there any chance you could provide network trace (Charles or Fiddler trace) that captures network trace information during which you are having this issue? 

@eldimious  Could you please share MSAL log with verbose logging on your MDM managed devices and also provide Charles network trace in .HAR format during which re-login is requested?

**Comment by NerevarineRule** [comment]
@joeypatino - 
Could you upgrade your iOS device to a higher version, like 14.5-6 and see if it changes anything? I do recall there was an issue with cookies in ASWebAuthenticationSession that had to be fixed by Apple - https://developer.apple.com/forums/thread/663533

@eldimious  
- what iOS version are you using?

Regardless, if you could kindly provide Charles trace log, that might help me to gather additional details. 

https://www.charlesproxy.com/

**Comment by eldimious** [comment]
@NerevarineRule  

Hey, our managed devices are using ios 14.4 / 14.2 / 14.6. Not sure how can i retrieve logs from a MDM managed device, but i think the issue is on `applicationContext.getCurrentAccount` or `applicationContext.account(forIdentifier: id)` cause this method do not return any account, so the flow of our code enters to `acquireToken` block

**Comment by NerevarineRule** [comment]
@eldimious  

Thanks for sharing the information. 

```
but i think the issue is on applicationContext.getCurrentAccount or applicationContext.account(forIdentifier: id) cause these methods do not return any account, so the flow of our code enters to acquireToken block.

Do you have any idea what is going wrong? Is something related to MDM+intunes, cause when we install it via testfligh in our devices seems is working properly?

```
1) Could you share your code block where you are acquiring token silently, interactively, as well as invoking those APIs?

2) To capture logs, here's the guideline on how to do so: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc

`While in our local devices the above flow seems is working and when we run it on managed devices, every time it re-asks the user to relogin.`

So this issue only occurs on devices that are MDM'd through Intune Company Portal apps? that's what I was hoping to see from the MSAL logs.
a) MSAL  logs from non'MDM'd devices where this issue doesn't occur
b) MSAL logs from MDM'd devices where this issue occurs.

And if possible, Charles/Fiddler network request would also be extra helpful.

**Comment by NerevarineRule** [comment]
@joeypatino 

After further investigation and discussions with other team members, it appears that the Authenticator/broker has their own dedicated cookie jar, which might be responsible for this issue with the SSO you are experiencing.

To address this issue - there are two other alternative ways - if you don't mind trying them out

1) in your WKWebview website, try creating your own infrastructure to save/retrieve the bearer access token you acquired through the MAM SDK.

2) MDM your device, which allows you to use Apple's SSO extension.

**Comment by joeypatino** [comment]
Hi @NerevarineRule, 

Thank you for this answer. I will follow up with my clients technical team (who developed the website) to see if they will be able to provide this infrastructure. 

Option 2 could be possible as well, although at the moment we are supporting iOS 12+, which doesn't appear to be compatible with the SSO extension.

I will work with my client on option 1 or 2 and follow up here if I have further questions. 

Thanks

**Comment by LibertyDev18** [comment]
Hi @NerevarineRule,

Was hoping to follow up on this to clarify one item as we have a very similar use-case that we are working on.

On Aug 6 you indicated that Authenticator has their own dedicated cookie jar and therefor an alternative mechanism would have to be put in place to support this. Does that still apply if Authenticator is not being used as the broker and instead handled with MSAL inside the app using ASWebAuthenticationSession?

To refresh, we are doing initial authentication natively with MSAL, then looking to access certain content in a web view which walks through another auth flow for the same account. Trying to determine any path to leverage the native MSAL information in the web view context to avoid multiple auth prompts.

Thanks!
