### ISSUE TITLE
Certificate prompt during acquireTokenWithParameters: in macOS 11.3.1 and greater

### ISSUE THREAD

**Issue by pmoprhy** [AzureAD/microsoft-authentication-library-for-objc#1353]
During acquireTokenWithWithParameters a set of identity preferences were created which suppressed a prompt (popup window) in safari but starting in macOS 11.3.1 those identity preference items in the keychain are not the same and the prompt is appearing .
![image](https://user-images.githubusercontent.com/1206821/127211155-096594ad-8ba7-4dab-95e7-960ea186796f.png)
Can we get that functionality back?

**Comment by mipetriu** [comment]
@pmoprhy Could I ask some clarifying questions - which type of webview are you using? Is it a WKWebview, or one of the system browsers? Also, does this certificate prompt come up every time since you've upgraded to a new version of MacOS?

Also, just for my own understanding, do you have any more details on the identity preferences that were set before?

**Comment by pmoprhy** [comment]
Not sure I understand the question. Our code is using the MSAL library, MSALPublicClientApplication to call acquireToken. The parameters sent to that call don't specify a WDWebview or browser, but it looks like safari gets presented. It appears to happen every time acquireToken is called since macOS 11.3.1. 
As far as the items in the keychain before I noticed these items used to be added into the key chain:
![image](https://user-images.githubusercontent.com/1206821/127247017-cc8c032b-93a8-4020-96cc-ec4428dfd9bd.png)
After macOs 11.3.1 this one item is added 
![image](https://user-images.githubusercontent.com/1206821/127247569-6a456dc1-9c9d-453f-a397-8cb81264d908.png)
and on that item, (not shown in screenshot), the “preferred Certificate” field is “not available”

**Comment by NerevarineRule** [comment]
@pmoprhy

Did you perform enrollment through MS Company Portal app on MacOS? The code that sets identity preference using MS device certificate resides in another library.

**Comment by pmoprhy** [comment]
We do start the process with Company Portal and then retrieve a token using the MSAL library with the certificate.

**Comment by NerevarineRule** [comment]
@pmoprhy Unfortunately, this is by design. Apple recently changed behaviors on their identity preference API. 

On MacOS, we use SecIdentitySetPreferred API to set identity preference for each of the trusted app path.

in versions of macOS prior to 11.3, identity preferences are shared between processes running as the same user. Starting in 11.3, URI names are considered per-application preferences. An identity preference for a URI name will be scoped to the application which created it, such that a subsequent call to SecIdentityCopyPreferred will only return it for that same application.
