### ISSUE TITLE
Getting error "Failed to get items from keychain"

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1404]
We're seeing the following for one our users, not sure what to suggest?

`2021-11-05 22:11:11 -0- MSAL: could not obtain account: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain.}`

**Comment by guidedways** [comment]
The user has since tried to reboot / re-install the app etc, to no avail. Not sure if there's something we need to do to support their setup? They've got admin privileges on the mac, however the mac is managed by their organization / via MDM. The app itself has been given permission to run by the network admin and they don't know why it continues to fail.

**Comment by guidedways** [comment]
@oldalton could we please have some help with this?

**Comment by guidedways** [comment]
Any help would be appreciated - we're not sure how to proceed.

**Comment by mipetriu** [comment]
@guidedways Sorry for the slow reply here. What is the scenario in which the user sees this error? It seems that this error code has to do with entitlements to access the keychain - do you know if the user gave access to the application to access their keychain? Also, would it be possible for you to provide more MSAL logs of the entire flow where this error occurs?

**Comment by guidedways** [comment]
They aren't prompted to give the app any entitlements to the keychain as the app hasn't stored anything in the key chain by the time this happens. 

They see this the moment the little window opens for Microsoft's login prompt / authentication. They have admin privileges on the mac but it's MDM managed (by the organization). 

What other part of the logs would you like to see? That's really mostly what it said.

**Comment by mipetriu** [comment]
@guidedways I see, so the user ran into that error during their initial sign-in attempt. I was hoping to see the MSAL logs for the entire login attempt to be able to understand the whole flow.

Looking into the error: "the error -34018 translates to errSecMissingEntitlement. This error means that your app is trying to use a keychain access group for which it does not have entitlements." - from this [Apple forum post](https://developer.apple.com/forums/thread/114456).

**Comment by guidedways** [comment]
Thanks @mipetriu but not sure what to do next - the keychain access related code is from within MSAL and any access group it's trying to use is again, from outside out control. Isn't this a MSAL issue?

**Comment by mipetriu** [comment]
@guidedways Another thing to check is if the necessary keychain groups were added to your application, according to the [MSAL doc](https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project).

**Comment by guidedways** [comment]
@mipetriu I have indeed - we have no other user complaining. In fact, if I try and disable keychain sharing and use our bundle ID as the keychain group, it gives me this exact error, which suggests it's working fine.

Could there be some system wide setting that's preventing MSAL from functioning properly out of the box? We're doing nothing special other than an interactive authentication. Their machine has been issued by their organization and MDM managed but as I mentioned earlier, their username has administrative rights.

**Comment by guidedways** [comment]
I had them run the following command for our app, as per Apple's Forum post:

`codesign -d --entitlements :- /path/to/your.app`

The keychain access group in there mentions both our bundle ID as well as:

```
OUR-TEAM-ID.com.microsoft.adalcache 
OUR-TEAM-ID.com.microsoft.identity.universalstorage
```

So this looks okay? Why else would this fail?

**Comment by guidedways** [comment]
Also, how can we enable extra logging? This is all I see:

```
MSAL silent authorization error: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain., MSALCorrelationIDKey=92ECB25D-E25B-4227-B6C5-1BB20664F306}
```

**Comment by mipetriu** [comment]
@guidedways If I understand your messages correctly, you observe that one user is experiencing the issue and the rest are not? It's possible that this user has had their keychain corrupted in some way. Has it worked before, or have they been experiencing the issue from the very beginning? Do you know if the user is able to use any other MSAL or Microsoft apps? Or maybe they could try to sign into the app on a different machine and see if the same thing happens? The user could also try to reset their keychain.

In order to enable more verbose logging, you can follow [this doc regarding logging in MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-ios?tabs=objc) and choose the verbose logging level.

**Comment by stealthmode404** [comment]
Hello @mipetriu! I am user in question here :) I am using Outlook for Mac successfully on my account and have been able to integrate it with my O365 account. Further, the default Calendars app is working as well, and have managed to integrate that as well with O365.

**Comment by guidedways** [comment]
@mipetriu That was the case until I tried this change:

`pcaConfig.cacheConfig.keychainSharingGroup = [[NSBundle mainBundle] bundleIdentifier];`

Now, even after removing this line, I cannot get my own login authenticated! It gives me the same error as it does for @stealthmode404 . 

```
Error Domain=NSOSStatusErrorDomain Code=-25293 "errKCAuthFailed / errSecAuthFailed:  / Authorization/Authentication failed." UserInfo={MSALErrorDescriptionKey=Failed to read stored item from keychain.}
```

Is MSAL caching the group ID or doing something else? I've never had this problem up until recently (the only other difference is that I pulled from `master` last night)

**Comment by guidedways** [comment]
Reading up on `kSecAttrAccessGroup` it seems this is only applicable in an iOS app - not macOS. MSAL's source code seems to discard this for macOS in a few places, but not in others. I'm going to try and dig deeper as it's now failing for me too.

**Comment by guidedways** [comment]
@mipetriu I can confirm that if I comment out all instances of `kSecAttrAccessGroup` for macOS, it works for me. I'm going to ask @stealthmode404 to try this out too.

Interestingly, I also noticed `kSecAttrAccessible` is being set for macOS - this isn't required. I've moved that into a `#if TARGET_OS_IPHONE` too in my fork.

**Comment by guidedways** [comment]
To elaborate, this is what I did everywhere `kSecAttrAccessGroup` was being set. Removed it from the default set of attributes:

```objc
#if TARGET_OS_IPHONE
  symmetricKeyAttr[(id)kSecAttrAccessible] = (id)kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;
  symmetricKeyAttr[(id)kSecAttrAccessGroup] = self.keychainAccessGroup;
#endif
```

**Comment by guidedways** [comment]
@mipetriu This change across all the places `keyChainAccessGroup` was used has fixed it for myself and @stealthmode404 . There should be a way to disable keychain sharing as it's not reliable on macOS as we've just seen.

**Comment by stealthmode404** [comment]
@guidedways thanks for your really great help with this! I was able to sync my O365 calendar with the new build that you had provided! 🥳

**Comment by guidedways** [comment]
@mipetriu Perhaps there are other places where MSAL's keychain fetch is breaking, but the now the initial login works for me, but as the token expires, a refresh fails with this:

```
Error Domain=NSOSStatusErrorDomain Code=-25293 "errKCAuthFailed / errSecAuthFailed:  / Authorization/Authentication failed." UserInfo={MSALErrorDescriptionKey=Failed to read stored item from keychain.}
```
:(

**Comment by guidedways** [comment]
For keychain sharing to work on macOS: https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps?language=objc

According to this `kSecAttrSynchronizable` must be set when `kSecUseDataProtectionKeychain` is used. MSAL does not seem to be doing that.

**Comment by guidedways** [comment]
I've been digging deeper as I feel although this solved the issue for @stealthmode404, I started seeing these errors at my end. Without the default Keychain Group, it would fail to work properly when obtaining tokens silently with `acquireTokenSilentWithParameters`. In fact, after looking at the logs carefully, I realized the keychain error wasn't showing at the point of logging in, in fact the user was able to login just fine - it was failing inside of `acquireTokenSilentWithParameters` each time.

It turns out the issue is on line 811 of `MSIDKeychainTokenCache`. It seems in other places, MSAL tries a second time to obtain the keychain item without `kSecAttrAccessGroup` (see `brokerKeyWithError` in `MSIDBrokerKeyProvider`). However, it does not do this in `MSIDKeychainTokenCache.m`. If I copy the same code over, it works:

```
    // Try to read previous format without keychain access groups
    NSMutableDictionary *query = [symmetricKeyQuery mutableCopy];
    [query removeObjectForKey:(id)kSecAttrAccessGroup];
```

I believe this is a bug in MSAL.

**Comment by guidedways** [comment]
In particular, this is all I had to do to make this work in `MSIDKeychaintokenCache`:

```
    CFTypeRef cfItems = nil;
    MSID_LOG_WITH_CTX(MSIDLogLevelVerbose,context, @"Trying to find keychain items...");
    OSStatus status = SecItemCopyMatching((CFDictionaryRef)query, &cfItems);
    MSID_LOG_WITH_CTX(MSIDLogLevelInfo, context, @"Keychain find status: %d", (int)status);

    // RETRY!
    if (status == errSecMissingEntitlement) {
      // Try to read previous format without keychain access groups
      [query removeObjectForKey:(id)kSecAttrAccessGroup];
  
      status = SecItemCopyMatching((CFDictionaryRef)query, &cfItems);
    }
```

**Comment by guidedways** [comment]
In addition I think the same block of code should be used everywhere `SecItemCopyMatching` is called with a `kSecAttrAccessGroup`.

**Comment by mipetriu** [comment]
@guidedways Regarding, `kSecAttrSynchronizable`, we prefer not to set it to YES since we don't want those items to sync with iCloud. After MacOS 10.15, it should be possible to use the `kSecUseDataProtectionKeychain` without needing to sync.

Thanks for providing info and background on the fix you applied to unblock @stealthmode404, I will take a closer look at your code and at the instances of `SecItemCopyMatching` in MSAL and get back to you.

**Comment by guidedways** [comment]
@mipetriu were you able to verify that the two places where it fetches keychain entries are being handled differently?

**Comment by mipetriu** [comment]
@guidedways Sorry for the delay, I hope you had a nice holiday weekend.

Regarding the different keychain fetch logic between `MSIDBrokerKeyProvider` and `MSIDKeychainTokenCache`, the code to try again without `kSecAttrAccessGroup` was added specifically to that class to cover a scenario regarding how multiple entitlements are read between the read and write cases. It's specific to that scenario, and shouldn't be added to the other instances of `SecItemCopyMatching`.

Looking back at your investigation, I realized that there is a potential issue in [the doc that describes the method to disable keychain sharing](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v2-keychain-objc?tabs=objc#disable-keychain-sharing). I believe that setting `pcaConfig.cacheConfig.keychainSharingGroup = [[NSBundle mainBundle] bundleIdentifier];` will disable keychain sharing properly on iOS, but I don't think that your app's bundle ID is in the entitlements by default on MacOS. In the entitlements that you mentioned @stealthmode404 had, I didn't notice your app's bundleId there. It's possible that this was the reason you started getting errors on your machine once you disabled keychain sharing in the above way.

Otherwise, I see the `-25293` error code, which I gathered to be normally related to keychain password issues. I see that in this [Apple forum post](https://discussions.apple.com/thread/2280636), someone was able to fix that type of issue by unlocking and re-locking their keychain. We have also seen some reports of this error code in some situations where the user was on a version of MacOS before 10.15, so I was curious what version of MacOS you're using?

Finally, I think it would be useful to submit a radar to Apple for the issue with @stealthmode404's keychain, as I believe their initial issue is specific to their machine and has something to do with the state of their specific keychain.

**Comment by guidedways** [comment]
You could call it a macOS issue, yes, but I don't agree with the explanation though. The code that handles "initial authentication" works (on machines affected by this), but the code that handles a silent refresh does not - simply because they're both not doing the same thing.

The machines tested are on Monterey macOS 12. I was able to reproduce this easily by using the bundleID to prevent keychain sharing (but that fails separately as a macOS issue perhaps). Either way, the simple fix of retrying without the groupID fixes it and works not just during our tests but also for the affected customers. Locking and unlocking the keychain won't work in this case as this is an entitlement issue, not a keychain access error per se. 

I insist that you reconsider. The code for both should be doing the same. I don't understand why the initial authentication should retry without the group ID but the silent refresh should not.

**Comment by mipetriu** [comment]
The code in `MSIDBrokerKeyProvider` should only be firing on MacOS if you are using the Enterprise SSO Extension, so the same keychain access code should be firing in both the interactive and silent auth cases.

I'm wondering if the behavior you are seeing could be explained in the following way:
1. The tokens retrieved during the initial interactive auth are saved with the bundleID as the access group to disable keychain sharing.
2. When searching for those tokens during silent refresh, MSAL is not finding them because the bundleID of the app is not added as an entitlement to the app by default on MacOS (it is on iOS). 

Could you try explicitly adding your apps bundleID as an entitlement under Signing & Capabilities -> Keychain Groups in XCode?

As MacOS versions past 10.15 use the iOS-style keychain, I don't think that there should be an extra check without the keychain access group added - although I do think that the documentation about disabling keychain sharing should be more comprehensive to note the above case, and there could be overall more options for this case. I'm discussing that with the rest of my team.

**Comment by guidedways** [comment]
Yes, so let me clarify:

1) If we use the bundleID to disable keychain sharing, the initial authentication flow works since it initially fails with the BundleID used as the Access Group, but then it fails during silent refresh since the silent refresh code does NOT retry without the Access Group

2) If we add our bundleID to "Keychain Groups" is **still** fails with the same entitlement errors. So we have no choice but to not use the bundle ID

HOWEVER - since we're not passing our bundle ID as the access group and relying on default behavior to work, for some uses (such as @stealthmode404) their mac is setup in some weird way (via MDM) that KeyChain sharing is either disabled or some other configuration is affecting keychain access - ALL attempts to get a keychain item with a Keychain Group fail with an entitlement error. I've verified via terminal that the app does in fact have the correct entitlements, but it continues to fail during silent refresh.

The only way to have this work during our tests and for @stealthmode404  was to retry one more time without the access group (thus effectively disabling keychain sharing). This works.

What I still don't understand is why you feel it's okay to retry during the initial auto (without the Access Group) but it's not okay during a silent refresh. If it failed for the user during initial authentication, it will continue to fail during silent refreshes too.

**Comment by menasheu** [comment]
Hi, I have this exact error message on iOS. 
This only occurs when I create an ipa file or put the app in production. As far as I use it in XCode there is no problem.
May I ask how did you solve your problem?

**Comment by guidedways** [comment]
This is how we fixed it: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1404#issuecomment-974776069

For whatever reason, MSAL is not using the same technique it uses during authentication for when it refreshes the token. Re-using the same code works.

**Comment by menasheu** [comment]
I am using the MSAL library as a black box, I understand I have to add it to the project and compile al together after the change?

**Comment by guidedways** [comment]
Yes, you need to fork MSAL, fix it there and use it directly with your project as source code.

**Comment by guidedways** [comment]
Unless @mipetriu would consider fixing this in code :)

**Comment by mipetriu** [comment]
@guidedways I hope you had a great holidays.

The `[query removeObjectForKey:(id)kSecAttrAccessGroup];` logic should not be activated in any normal authentication flows that do not use the Enterprise SSO extension. The retry logic should not be running in this case, so I'm confused about point 1. in your previous message.

After discussing with my team about this issue, we're thinking that a way to properly address it would be for MSAL to offer a new flag that developers could turn on - if the flag is set, MSAL would write keychain items to the default access group, or in other words with no access group set at all.

Would setting a flag like this fix the issue?

**Comment by guidedways** [comment]
Thank you!

I'm not sure if it would. I'm still confused as to why it shouldn't retry the same way it does during initial auth. I don't think it's about the default group vs the app group - customers this fails for are unable to use any access group (probably due to how their machine has been provisioned - I still don't know what causes it) but essentially the fix worked for all of them, I.e the retry block with the keychain group removed. 

The flag may not help as we want to be able to try with the access group first and then without if it fails (just as MSAL does initially). Ever since we deployed our patch we have had no further complaints.
