### ISSUE TITLE
Trouble with changing accounts - Even with promptType = .login

### ISSUE THREAD

**Issue by br-johndavis** [AzureAD/microsoft-authentication-library-for-objc#1409]
In the course of using MSAL I'm trying to change accounts as part of testing use-cases requiring various roles and permissions. 

As such, I'm needing to swap between user1@domain.com and user2@domain.com. 

After signing out from user1, I tap login, then  tap "additional account". The user then gets the first prompt to enter their email. Instead of being taken to the username and password screen, though, they instead get the "provide app access to this user" screen for the previously logged out user.

I'm invoking `.remove(account)` on sign out, and I ensure that the prompt type is `.login` when acquiring the token is interactive. 

Is there something else I'm missing here?

**Comment by mipetriu** [comment]
@br-johndavis Could you tell us more about your implementation? What type of webview are you using for interactive requests with MSAL? Also, just to confirm, you're using [this](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)signoutWithAccount:signoutParameters:completionBlock:) API to signout?

**Comment by rockgecko-development** [comment]
I have a similar problem, but just by logging out, not using 'additional accounts'. My setup:
- iOS simulator
- iOS app calls `acquireToken` to log in to an AD B2C directory
- "app wants to use b2clogin.com" dialog
- safari view controller opens
- user enters a username and password (B2C local account)
- logout via `MSALPublicClientApplication.remove(account)`
- attempt to log in again via `acquireToken`
- "app wants to use b2clogin.com" dialog
- safari opens, redirects, and closes again without user interaction
- user is now logged back in to the same account, unable to switch to a different account

**Expected result:**
Safari view controller loads the sign in page so user may enter local account details for same or different account.

This was working fine a few days ago. Not sure if it's related to a pod version update, or possibly a change occurred in AD B2C itself?
This is occurring on iOS simulator, but doesn't seem to occur on an actual iPhone. The only way I was able to switch users on the simulator was to clear safari cookies via system settings, or reset the simulator.

**Comment by br-johndavis** [comment]
@mipetriu 

I'm clear what you mean by the "type" of web view. I configure my params like so:
`let webViewParams = MSALWebviewParameters(authPresentationViewController: from)`
- `From` is a parent view controller that presents the auth web view. 

I configure my interactive params like so:
`let parameters = MSALInteractiveTokenParameters(scopes: scopes, webviewParameters: webViewParameters)
`parameters.promptType = .login`

And acquire token like so:
`applicationContext.acquireToken(with: parameters) { ... }`

**Comment by mipetriu** [comment]
@br-johndavis, @rockgecko-development 

If both your scenarios are using the SafariViewController or ASWebAuthenticationSession, its possible that this issue could be caused by Safari cookies being left over in the system browser after your first sign-in. I see that in both cases, the account is being removed using the `.remove` API, which only removes the account info from the cache and doesn't do the extra step of removing the account from the system browser (see the description [here](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)removeAccount:error:)).

Passing `promptType = .login` will ensure that the system browser is popped up, but if there are still uncleared cookies from the previous signin, it will default to using those first before accepting user input.

Do you mind trying `.signout`, which should clear those cookies, rather than `.remove`? (See the description [here](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)signoutWithAccount:signoutParameters:completionBlock:)).

**Comment by rockgecko-development** [comment]
Thanks for this info. After more investigation I have found that this issue occurs on an iOS 14.5 simulator, but NOT on iOS 14.2 simulator or real 14.2 device. This is very surprising!
Repro steps: as per https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1409#issuecomment-966871963 . The iOS 14.5 simulator has user agent `Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Mobile/15E148 Safari/604.1`. 

It would be interesting to see the actual url passed to the Safari view controller, to check it's the same for both simulators. If it is, then this is likely a problem in the AD B2C platform itself (or Safari), rather than this plugin. It also doesn't seem to matter which version of this plugin I use.
But I'm not sure how to see it.

I also have AppleId set up as an identity provider in my B2C. If I use that on the simulator, then after logging out and returning, it immediately redirects to an appleId page, and I still need to enter an email and password. Here, there is no way to switch to a different local account or other social account, but at least I could switch to a different AppleId.

If the issue is only with this specific iOS simulator then I don't really care, but if it affects a number of real iPhones then it will be difficult for those users to log out without them clearing all safari cookies.
I am reluctant to switch to the `.signout` function, which would pop up the system browser unnecessarily, given it works on other OS versions (and on Android).

**Comment by suchithm** [comment]
Observed the similar issue while deploying to iPhone, Simulator looks good.
