### ISSUE TITLE
Account claims refresh issue

### ISSUE THREAD

**Issue by lzouloumis** [AzureAD/microsoft-authentication-library-for-objc#1461]
Hello,

Is there any way to refresh the account claims  when using the acquireTokenSilent method?

We have noticed that account claims refresh only when we use acquire token method interactively. However, we don't want to require the user to log in again, each time a custom claim in our account claims changes.

Thanks for your time.

**Comment by ThomasPapapaschos** [comment]
I have the exact same problem.

**Comment by hieunguyenmsft** [comment]
@lzouloumis @ThomasPapapaschos can you elaborate about your flow and what kind of claim?

**Comment by lzouloumis** [comment]
Hello @hieunguyenmsft,

First of all I would like to thank you for your prompt response. Before I delve into the details of the flows and the claims I would like to mention that we integrated MSAL via CocoaPods and we use the latest version. Below there is a code snippet from the MSAL-Info.plist file.
`  <key>CFBundleShortVersionString</key>
  <string>1.1.26</string>`

The claim that we want to refresh is custom and it is defined in azure portal. Below there is a code snippet with the structure of the claim.
`      - key : "extension_Sapids"
        - value : {"SapIds":["9999999999:4","9999999991:3,4"]}`

 It is just a string value that contains a JSON. It is not a default claim such as the **kid** that is returned as part of the id_token.

 The flow that we use is the refresh token flow. To be more precise we call the **acquireTokenSilent** method  with forceRefresh parameter set to true in order to skip the token cache and force the library to refresh the accessToken. Although the accessToken is refreshed after calling the acquireTokenSilentMethod, the account claims object still has old values. We have to mention that the Graph API that connects with B2C returns fresh data for the key **extension_Sapids**. However, our account claims is stale. If the backend service tries to decode the newly acquired access_token that the refresh token flow returned, old values will be returned.

The only way we have managed to get the new values for this claim each time this JSON is modified is through the interactive login. This means that every time this claim is modified we have to log out the user and prompt him to log in again in order to have the new values for this claim in the account claims object. This is not a good experience for the user.

We would like to know if there is a way to force the library to return the new value in account claims. For example if we could use a claims request. We have tried to use claims request in parameters but we failed. I mention again that if we call a Graph API from Microsoft we have the new value for this claim. Only the token in MSAL contains stale data.

Below there is a code snippet from the flow we use.
`        let msalParameters = MSALParameters()
        msalParameters.completionBlockQueue = DispatchQueue.main
        application.getCurrentAccount(with: msalParameters, completionBlock: { (currentAccount, previousAccount, error) in
            guard let currentAccount = currentAccount else {execute();return}
            let tokenParameters = MSALSilentTokenParameters(scopes: ConfigurationParameters.kScopes, account: currentAccount);
            tokenParameters.forceRefresh = true
            self.application.acquireTokenSilent(with: tokenParameters, completionBlock:{(result, error) in
                guard error == nil, let result = result else {execute(); return}
                self.applicationLoginData = result
                execute()
            })
        })`

We need help because we need to deliver the project to the client as soon as possible.


Thanks for your time. If the information is not sufficient please inform me so that I respond immediately with appropriate information.

Sincerely,
Lampros Zouloumis

**Comment by hieunguyenmsft** [comment]
Hi @lzouloumis, I was thinking of suggesting you follow this article:
https://docs.microsoft.com/en-us/azure/active-directory/develop/request-custom-claims to force-request the custom claim in each request but then realized that your flow is B2C so that solution might not work for B2C flow. I forwarded your question to our B2C team, will keep you posted.
Thanks,
Hieu.

**Comment by lzouloumis** [comment]
Hello @hieunguyenmsft,

We have already tried to solve our problem using the article that you mentioned. Specifically, we have created a custom claims request and we used the property "value" to force the library to return the specific value for our custom claim.
However, it didn't work. It returned back the old claim value and not the value that we have specified in the claims request.

We will be waiting for the B2C team to answer us.

Thank you,
Lampros

**Comment by lzouloumis** [comment]
Hi @hieunguyenmsft,

Any news for this issue?

Thanks,
Lampros

**Comment by hieunguyenmsft** [comment]
Hi @lzouloumis , I haven't heard anything from the B2C team. I will ping them again today.
Thanks,
Hieu

**Comment by HarmanDhunna** [comment]
Hello @lzouloumis,

Please take a look at the paragraph in [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect#refresh-the-token) doc. 

Currently (and most likely for the foreseeable future) B2C does not support updating the claims (other than the ones listed in the doc above) when redeeming refresh tokens. From my research on other GitHub issues, this seems to be intentional behavior. 

 The recommended way to get obtain updated claims is to utilize the userinfo endpoint. This is more of a complete solution, as if you were to utilize other IDPs, they would also utilize userinfo endpoint for updated claims. Here is a link to learn more about setting up userinfo endpoint: [Userflow ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/userinfo-endpoint?pivots=b2c-user-flow) vs [Custom policy](https://docs.microsoft.com/en-us/azure/active-directory-b2c/userinfo-endpoint?pivots=b2c-custom-policy)
