### ISSUE TITLE
Acquiring Device Id from decoding AccessToken in iOS

### ISSUE THREAD

**Issue by MohamedJaffer-24** [AzureAD/microsoft-authentication-library-for-objc#1485]
Is it possible to fetch Device Id by decoding the base 64 Encoded AccessToken?

Device Id -> In Microsoft Authenticator App, After Device Registration , there will be a device id shown there.

At First, I was able to see the Device Id after decoding the access token. But then After when i try it by changing the Microsoft Account ,I cant get it again. I can only get the Access Token, but on decoding it, "deviceid" key is not present.

Kindly check this ,if it is an issue or Guide me in a proper way to fetch the device Id.
attached Screenshot for the account's deviceid.
<img width="279" alt="Screenshot 2022-05-13 at 5 16 02 PM" src="https://user-images.githubusercontent.com/60511157/168276904-9a528ff8-452a-4eb7-a2d8-6b3356b73b41.png">

**Comment by antrix1989** [comment]
May I know why you need the device id? We don't support getting it from the access token.

**Comment by umapriyadarsi** [comment]
We sync the list of devices from Azure AD and are trying to create an inventory of the list of devices which are present in our inventory. We are able to do this already for Windows devices(The certificate is present in Windows Certificate Store. The Certificate subject ID is the Device ID which matches with Azure AD REST API data for /devices).

We are now also trying the same for iOS.

We got to know that this is possible, by looking into the following GitHub issues : 
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1204
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/883

**Comment by umapriyadarsi** [comment]
@antrix1989 any update on this? Would appreciate your view on how this can be achieved?

**Comment by juan-arias** [comment]
Hi @umapriyadarsi, we no longer support decoding the access token in order to get the device id. Getting it is now an internal system operation and not supported for 3rd party developers; nevertheless, we would like to know more about what is the objective you are trying to achieve once you get the device id.

If the end goal is to make sure the device is registered, we suggest configuring a resource to be accessible by a registered device only through a Conditional Access Policy.

**Comment by umapriyadarsi** [comment]
@juan-arias is my understanding correct that at least as late as 25th Feb 2021 this was supported as mentioned by @oldalton here : https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1204#issuecomment-785305664
?

The end goal is to create an inventory of the devices joined with Azure Ad.

**Comment by oldalton** [comment]
@umapriyadarsi, we never supported or recommended for clients to decode access tokens directly. Access tokens are meant for resources/APIs and shouldn't be decoded by clients. If you have a scenario where your API requires a deviceId, you can request deviceId through a custom claims parameter just like you did. However, this access token shouldn't be decoded by the iOS client app. We have this documented in more details here: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

However, if what is happening is that:
1. you're requesting custom deviceId claims
2. sending your access token to a web API
3. web API is failing because it doesn't see the expected deviceId

Then please provide both MSAL and Authenticator logs for our investigation. However, if you're not performing all the steps described, then please provide additional clarification on your scenario, and why you're skipping one of those steps.

**Comment by umapriyadarsi** [comment]
@oldalton I am not particularly about the access token. We are mainly looking to get the DeviceId. 

We have been trying various things, and we were able get the DeviceId in iOS twice by base 64 decoding the access token. 
In Android, we are able to consistently receive the deviceId, by base 64 decoding the access token. So, we began with that assumption. That is the only link for access token. Otherwise, we are not concerned about the access token having the deviceId.

If you can share some documentation or code-snippet through which we can extract the DeviceID from Authenticator/MSAL that would be very helpful for our use case : creating an inventory of devices which are Azure domain registered. Issue https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1204#issuecomment-785305664 clearly mentions that they 'failed to retrieve the Device ID' , so this seems something which is possible.

**Comment by oldalton** [comment]
@umapriyadarsi, thanks, in this case I recommend requesting this in the "id_token". 
You can try to explicitly request a deviceId claim using this parameter: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALClaimsRequest.html

Configure it with the following JSON: `{"id_token":{"deviceid":{"essential":true}}}`

Unfortunately, I cannot guarantee it will work since we don't really support returning just a "deviceId" in our system, but this is what I'd try doing.

**Comment by MohamedJaffer-24** [comment]
@oldalton  Thank You  . This Custom Claims Method for fetching deviceid , worked great .
Can you please close the ticket and thank you everyone for helping on this.

**Comment by mroen1** [comment]
> Windows

Can you elaborate how you grab the DeviceID from a Windows workstation. We a re unable to do so in a web applicaiton.
