### ISSUE TITLE
Issue in Self signed mac pkg file related to keychain!!!!

### ISSUE THREAD

**Issue by parora9594** [AzureAD/microsoft-authentication-library-for-objc#1499]
Hi,
We are integrating MSAL in our Mac Application to register on Azure portal. we are getting bellow error in signed build only while running from xcode everythig is working fine.

`MobiControl[40882]/1#-1` LF=0 copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "Client explicitly specifies access group ASDSDSDDWW.com.microsoft.identity.universalstorage but is only entitled for (

    "com.apple.token"

)" UserInfo={numberOfErrorsDeep=0, NSDescription=Client explicitly specifies access group ASDSDSDDWW.com.microsoft.identity.universalstorage but is only entitled for (

    "com.apple.token"

)}
MobiControl[40882]/1#-1 LF=0 delete Error Domain=NSOSStatusErrorDomain Code=-34018 "Client has neither com.apple.application-identifier nor com.apple.security.application-groups nor keychain-access-groups entitlements" UserInfo={numberOfErrorsDeep=0, NSDescription=Client has neither com.apple.application-identifier nor com.apple.security.application-groups nor keychain-access-groups `entitlements}`

Steps we are following:
->We have enrolled our device into MDM
->than pushed company portal app on device 
->SSO Payload onto device.
->on Debug(while running from xcode) when we try to register and call interactively flow it open SSO company portal extension and everythig works file.
->**In case of signed production build we getting above error. can some one help in this.**
We have checked and recreated our provisioning profile also but no success, we have added active domain capability also.

**Comment by parora9594** [comment]
@antrix1989 Please help.

**Comment by juan-arias** [comment]
Hi @parora9594, 

Since you mention it works when running from Xcode, I'm assuming you already have a correct *.entitlements file and an entry for Debug, so an entry for Release might be missing.

Please check on your project -> your target -> Build Settings -> Code Signing Entitlements 
and make sure you have entries for Debug and Release (they can both point to the same *.entitlements file), for example:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/1686668/171733110-65e5b9a8-bb67-4906-b821-80843458c45c.png">

**Comment by juan-arias** [comment]
Please feel free to reopen in case issue persists.
