### ISSUE TITLE
error: Unable to create RSA key with the provided exponent and modulus?

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1505]
I'm not sure what this even means but one of our users is seeing this. Any help please?
![img-0](https://user-images.githubusercontent.com/202437/172200687-2c98fe82-91a2-4500-b4c1-216f92935eea.png)

**Comment by ameyapat** [comment]
Hi @guidedways ,thanks for bringing this to our attention. This error might be thrown by our token service due to a bug in device registration for some macOS devices. To confirm, can you ask the user to create an incident by opening company portal app -> Help -> 'Send diagnostic report'. Please share the incident ID here

**Comment by guidedways** [comment]
Thanks - they don't know what that means (I.e how to do that).

**Comment by ameyapat** [comment]
Please ask them to follow these instructions : https://docs.microsoft.com/en-us/mem/intune/user-help/send-errors-macos#share-diagnostic-details

**Comment by hieunguyenmsft** [comment]
Close as no logs provided.
