### ISSUE TITLE
Sign-in with MSAL for status bar app fails without window

### ISSUE THREAD

**Issue by frindler** [AzureAD/microsoft-authentication-library-for-objc#1508]
I have a macOS status bar app and would like to sign in the user when the app starts. I'm using MSAL 1.2.1 installed via Cocoapods.

If no user is logged in (if I cannot acquire a token silently), I call the following function from `applicationDidFinishLaunching` in my app delegate: 

```
func acquireTokenInteractively() {

        guard let applicationContext = self.applicationContext else { return }
        guard let webViewParameters = self.webViewParameters else { return }

        let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
        parameters.promptType = .selectAccount

        applicationContext.acquireToken(with: parameters) { (result, error) in

            if let error = error {

                NSLog("Could not acquire token: \(error)")
                return
            }

            guard let result = result else {

                NSLog("Could not acquire token: No result returned")
                return
            }

            self.accessToken = result.accessToken
            NSLog("Access token is \(self.accessToken)")
            self.updateCurrentAccount(account: result.account)
        }
    }
```
(this is essentially the version from the [MSAL macOS/iOS example](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios))

Because it's a status bar app at this point there is no window (it will only be displayed when the user clicks the status bar icon) and this fails with:

```
Could not acquire token: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start., MSALCorrelationIDKey=965EBECF-4535-4111-B59A-0395F29D48C0}
```

If I call `acquireTokenInteractively()` from a displayed window it works just fine (displaying the login page in the browser and successfully acquiring a token).

It seems to me that this should work even if no window is displayed since it uses the browser for login anyway.

Is this a bug or is there a workaround? Thanks in advance!

**Comment by kaisong1990** [comment]
@frindler Thanks for your question.

The error message is thrown by Apple system instead of MSAL libs. There is a requirement since iOS 13 and macOS 10.15 that an anchor window is required in order to use ASWebAuthenticationSession.

Here is the reference: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationpresentationcontextproviding/3237230-presentationanchorforwebauthenti?language=objc

In your scenario, when user is not logged in yet, I would suggest showing a little dropdown window displaying signing in/connecting from the menu bar, which can be used as the anchor window and triggering the ASWebAuthenticationSession, this will also let user know that the signing in process was triggered by your app, not randomly from other apps.

**Comment by frindler** [comment]
@kaisong1990 Thanks for the quick reply. That sounds like a good workaround to this macOS issue!
