### ISSUE TITLE
MSALPromptType type `.login` shows the sheet but auto logs in.

### ISSUE THREAD

**Issue by SpoonTheGreater** [AzureAD/microsoft-authentication-library-for-objc#1525]
Using the default `webviewType` for the `MSALWebviewParameters`, default values for the `MSALInteractiveTokenParameters` and setting the `promptType` to `.login` `acquireTokenWithParameters` always shows the web view sheet, but redirects to successful login without requiring user to enter username or password. 

Using `signoutWithAccount` to sign out, but the web view cache isn't being cleared. Even when `wipeCacheForAllAccounts` or `wipeAccount` are flagged true on the 'MSALSignoutParameters'

Setting `keychainSharingGroup` to the apps keychain sharing or leaving it at the default (and adding `com.microsoft.adalcache`) doesn't seem to make a difference.

This happens on real devices running iOS 15
MSAL 1.2.2
Swift and UIKit

Is this expected behaviour or am I missing something?

**Comment by mipetriu** [comment]
@SpoonTheGreater As part of the MSALSignoutParameters, could you try to set the `signoutFromBrowser` param to true?

```
let signoutParameters = MSALSignoutParameters(webviewParameters: self.webViewParameters!)
signoutParameters.signoutFromBrowser = true
```

Another question: are you using SSO extension in your scenario?

**Comment by danielfarrell-transact** [comment]
Thanks @mipetriu!

We've tried setting `signoutParameters.signoutFromBrowser = true` and we get the following strange behaviour (see video) and when the user attempts to re-enter the app they're not prompted for username / password.

https://user-images.githubusercontent.com/65712630/181770135-4c7421e1-6e99-4e30-8b1a-027cb5ec144a.MP4

**Comment by mipetriu** [comment]
@danielfarrell-transact, this is the expected behavior for the `signoutFromBrowser` param - we need to invoke the browser to complete that signout.

I do see that the user is not being prompted after the signout in your video. Would it be possible for you to provide MSAL logs of this behavior occurring so I can take a closer look? You could attach them here or send to mipetriu@microsoft.com if you'd prefer.

**Comment by mipetriu** [comment]
@danielfarrell-transact Thanks for sending the log, and apologies for the delay. From what I can see, this is a B2C scenario. That would explain why the `signoutFromBrowser` param didn't solve the issue - it does not work in the B2C case.

Based on this, my suspicion is that there is an issue here with SSO cookies not being cleared in the browser. I'm personally not extremely familiar with all the configuration and policies in B2C, so I've asked for some help from B2C experts within Microsoft.

Since it seems to be related to cookies in the browser, would it be possible for you to also provide a network trace? That way we can confirm how the cookies are behaving.

**Comment by danielfarrell-transact** [comment]
Hi @mipetriu - I've just sent a network trace to your email as both `.trace` & `.chlsj` (Charles Proxy) files. Let me know if you need it in another format.

This is a network trace of the following:
Initial login > Logout > Login again with no prompt for users credentials

`wipeCacheForAllAccounts` & `wipeAccount` signout parameters were both set to true.

**Comment by mipetriu** [comment]
Hi @danielfarrell-transact, thanks for sending that info. After speaking to our B2C team, they are thinking that the issue lies with the mock SAML IDP that you are using. When MSAL passed `promptType = login` to B2C, it will make a request to the mock IDP with `ForceAuthN = true`. It appears that the mock IDP does not recognize the `ForceAuthN` param, and in this case B2C is working as expected.

**Comment by danielfarrell-transact** [comment]
Okay, thank you for your help @mipetriu 👍🏻
