### ISSUE TITLE
Issue with the login - ios16 beta7

### ISSUE THREAD

**Issue by smarapat** [AzureAD/microsoft-authentication-library-for-objc#1540]
Hi team,
The login is not working in ios16 beta7. I have upgraded to the latest MSAL plugin but still facing the same issue.

Could you please help me?

**Comment by juan-arias** [comment]
Hi @smarapat, can you please try again with iOS16 beta 8?
Also, please provide logs or additional information about what specific issue you are having.

**Comment by smarapat** [comment]
Hi @juan-arias , still I'm facing the login issue.

Couldn't query current account with error: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain.}

**Comment by juan-arias** [comment]
Hi @smarapat,

Looking into the error: "the error -34018 translates to errSecMissingEntitlement. This error means that your app is trying to use a keychain access group for which it does not have entitlements." - from this [Apple forum post](https://developer.apple.com/forums/thread/114456). Please check if the necessary keychain groups were added to your application, according to the [MSAL doc](https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project).

Does your app work on iOS 15? Do you have the option to do a factory reset to the iOS device and try again?

**Comment by juan-arias** [comment]
Hi @smarapat, can you double check the entitlements file? I'm able to reproduce your error message if I have it like this
`com.microsoft.adalcache`:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/1686668/191583350-e1a7821e-b882-4c1a-ad29-32e1a71e3ac0.png">

instead of `$(AppIdentifierPrefix)com.microsoft.adalcache`.

If your entitlements file is correct, are you able to share a sample app? otherwise can you try our [ios sample app](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) and share it with us?

**Comment by priya-mobiquity** [comment]
@antonioalwan @juan-arias I am facing same issue... It is working with build generated by xcode 13 and not working with xcode 14.

Entitlement and all other settings are the same.

**Comment by priya-mobiquity** [comment]
@juan-arias We have a release planned and everything is updated for xcode 14.  Request you to help us with this issue asap.

**Comment by juan-arias** [comment]
Hi @priya-mobiquity, we are not getting an error with xcode 14 and iOS 16/15. Can you try the [ios sample app](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) and let us know if you have any issue with it? Otherwise can you provide us a sample code where the issue can be reproduced so we can take a look?

**Comment by priya-mobiquity** [comment]
@juan-arias Did you test in release version i.e release a build to app center/testflight... Login and kill the app, It will ask again for login.

**Comment by juan-arias** [comment]
@priya-mobiquity, can you check your Build Settings? Maybe your project doesn't have the Entitlement file selected for Release, or you might have a different file for Release, for example:
![image](https://user-images.githubusercontent.com/1686668/195398866-f516de52-1ccc-4c22-9ea3-6f203e9abb1a.png)

or maybe you have different configuration for Keychain Sharing for Debug/Release (with separate files), for example:
![image](https://user-images.githubusercontent.com/1686668/195399803-a1a1bb2c-2c60-4971-99a6-437e17bd3358.png)

**Comment by priya-mobiquity** [comment]
@juan-arias 
I have only 1 configuration for both debug and release mode.
Also, entitlement is selected in Build Settings.

Do you think we need to clear keychain group at start (if any func is available in lib) or may be some other setting is failing in release mode.

**Comment by priya-mobiquity** [comment]
@juan-arias Thank you!
Issue was related to entitlements file with xcode 14 azure pipeline.
