### ISSUE TITLE
iOS- AcqureTokenSilently gives old access token

### ISSUE THREAD

**Issue by hassanelshairr** [AzureAD/microsoft-authentication-library-for-objc#1572]
when user is logged in by MSAL login in iOS app , and after some time, token got expired so we use AcqureTokenSilently it works sometimes, but in sometimes gives old access token and this make all requests fails,
So I need help, how to figure out a solution that give me a new token not expired one

**Comment by antonioalwan** [comment]
@hassanelshairr Thanks for your question. In the case when AcquireTokenSilenty fails that indicates that an interactive call will be required to continue the flow.

Please refer to this example [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-acquire-token).

**Comment by priya-mobiquity** [comment]
getTokenSilently is not working properly on iOS 16 build with xcode 14.
Each time we open the app, interactive login screen is asked

**Comment by antonioalwan** [comment]
@priya-mobiquity please share logging error so that we have a better understanding of the flow. You can collect Verbose logs as described [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-error-handling-ios).  I would also suggest verifying that the steps listed at [Configuring MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal) for keychain setup are considered.

**Comment by priya-mobiquity** [comment]
@antonioalwan I get this "Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain.} "

while fetching allAccounts

**Comment by antonioalwan** [comment]
@priya-mobiquity, Same error is reported in [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1540). Please take a look and let me know if you have questions.

**Comment by antonioalwan** [comment]
Closing as it is a duplicate issue.
