### ISSUE TITLE
How can I refresh access token inside watchOS application ?

### ISSUE THREAD

**Issue by ychie** [AzureAD/microsoft-authentication-library-for-objc#1625]
Hi!

Is it possible for watchOS application to somehow refresh access token by itself? As I can see MSAL doesn't have watchOS support, so I cannot authenticate user inside watch application and also I cannot find any public interface that would allow me to save refresh token from iOS application and acquire new access token by myself via network request.

**Comment by juan-arias** [comment]
Hi @ychie, as you mention MSAL does not have watchOS support. Can you try using this [API](https://developer.apple.com/documentation/watchconnectivity/wcsession/1615687-sendmessage) to refresh the access token in the companion app instead of in the watch, and then send to the watch the renewed access token.

**Comment by ychie** [comment]
Resolved my problem by using API proposed by @juan-arias. Thanks for the help!
