### ISSUE TITLE
Is there a way to avoid showing dialog [<app name> Wants to Use "microsoftonline.com" to Sign In]?

### ISSUE THREAD

**Issue by alexeystrakh** [AzureAD/microsoft-authentication-library-for-objc#1649]
With no MS Authenticator on iOS device, I activate webview MSAL flow to authenticate a user. Is there a way to avoid showing dialog [<app name> Wants to Use "microsoftonline.com" to Sign In? This allows the app and website to share information about you]? This dialog appears every time I call `acquireToken` (interactively) on my MSAL app instance:

I have checked parameters [MSALWebviewParameters](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html) and [MSALInteractiveTokenParameters](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html) and wasn't able to identify a way to disable this prompt.

How can I disable this prompt or at least show it for the very first authentication only?

<img width="254" alt="image" src="https://user-images.githubusercontent.com/3697084/214948611-5b86e63d-f751-4982-9171-22b8cf4936be.png">

**Comment by mipetriu** [comment]
Hi @alexeystrakh, this dialog is shown by Apple as part of using ASWebAuthenticationSession as a system browser for the interactive login. If you'd like to not see the prompt, you could configure MSAL to use a WKWebView rather than a system browser through [MSALWebviewType](https://azuread.github.io/microsoft-authentication-library-for-objc/Enums/MSALWebviewType.html). You can find more info about the implications of choosing either webview option in this doc: https://learn.microsoft.com/en-us/azure/active-directory/develop/customize-webviews.

**Comment by alexeystrakh** [comment]
Thank you, that answers my question. Glad to know that this is part of the Apple's ASWebAuthenticationSession. With WKWebView and SafariViewController type this prompt is not shown although session info loses some information (WKWebView).
