### ISSUE TITLE
[Unity] Issues setting up MSAL for iOS in Unity

### ISSUE THREAD

**Issue by Kibsgaard** [AzureAD/microsoft-authentication-library-for-objc#1774]
We are setting up MSAL (and Intune) for an application build in Unity. The application is both for iOS, Android, and Windows. The initial focus is on setting it up for iOS.

1. We would like to know if there are any tools/documentation for setting this up with Unity (prefable with multiplatform setup)?
2. When Unity outputs an xcode project, there is both a Unity-iPhone and a UnityFramework project. Which one of these should the Intune/MSAL frameworks and keychan groups be setup on?
3. When following the [MSAL configuration guide](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal) the "iOS only steps", step 3 says to handle the callback in appDelegate. Do you have an example of what this looks like for a Unity application (there are no appDelegate nor UISceneDelegate in the generated xcode projects).
4. Do you have any tips on how to manage the Intune/MSAL setup in a Unity project where the xcode project is generally regenerated on each build?

We were directed to ask the questions here by Microsoft Premier Support (case 36287143).

**Comment by juan-arias** [comment]
Hi @Kibsgaard 
We don't explicitly support Unity, but I'll try to help.

1. There is no documentation specific for Unity, and this library is specific for iOS & macOS but you might find help in Unity's community pages.

2. They should be added to the `Unity-iPhone` target, since that's the one that will be running the game/app.

3. You can do the changes to the file `UnityAppController.mm`, it contains the `application:openURL:options:` method. Don't forget to add `#import <MSAL/MSALPublicClientApplication.h>`.
Also, in Unity Player Settings for iOS, set the `Target minimum iOS Version` to 14.0 if you want to get the latest MSAL library and the latest Xcode.
Additionally, you might also want to have your Podfile like this:
```
use_frameworks!

target 'Unity-iPhone' do
end

target 'UnityFramework' do
    pod 'MSAL'
end
```

4. You might try with Unity's plug-ins, that way the regenerated project would contain the required changes.

Another option you might want to research is [MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) since you also plan to support other platforms and the integration might be easier. But I'm not sure if Unity is supported or not.
