### ISSUE TITLE
Implement Error Protocols for MSALError for better Swift compatibility

### ISSUE THREAD

**Issue by brandwe** [AzureAD/microsoft-authentication-library-for-objc#191]
We have a few things we could do to make the our Swift developers have an easier time, which is all around changing some things so that the Objective C -> Swift bridge makes better decisions on how to expose our methods. 

The most urgent thing that stands out to me though is the fact that our MSALError is wrapped. This is passable in Objective-C:

```objective-c
if ([error.domain isEqual:MSALErrorDomain] && error.code == MSALErrorInteractionRequired)
```
But becomes brutal in Swift with the need to downcast and grab raw values:

```swift
if (error! as NSError).code == MSALErrorCode.interactionRequired.rawValue
```

This is easily fixed by implementing a Protocol so that the Swift bridge can expose our errors elegantly, such as:

```swift
do { 

 try {
// Acquire token silently
 } catch MSALError.interactionRequired {

// Acquire token interactively. 
       }
 }
```

**Comment by RPangrle** [comment]
There is no MSALError class in MSAL. We use system standard NSErrors. Apple should be doing something to make sure they're own NSError class is more easily consumer in Swift.

**Comment by brandwe** [comment]
Care to comment @oldalton since we discussed the need for this in Slack? I see it as beneficial to have our own Error protocol.

**Comment by oldalton** [comment]
@brandwe I definitely agree that current implementation results in an awkward code, however the proposed solution won't fix it. Please see how there's lack from Apple documentation on handling asynchronous errors (great link sent from Ryan) :( https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html

I would suggest to keep this issue open and see what solutions are available if any. Maybe Apple will provide an update for this issue in future.

**Comment by RPangrle** [comment]
Also, the error is not wrapped. Error is simply a protocol for "anything that can be thrown as an error," and because Error has no requirements as a protocol, it means it can be practically anything. Considering we're handling NSErrors just like how it is used in system APIs we aren't asking anything more then what Apple is already asking Swift developers to do for Apple's own APIs. Straying from that means that we force the developer to learn even *more*.

If you look at this document: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html in Swift 2 Apple started automatically boxing NSErrors in synchronous methods, in Swift 3 they removed ErrorType and left us with just the Error protocol. Presumably once Apple figures out how they want to properly handle async code in Swift they'll tackle this as well.

**Comment by brandwe** [comment]
Great conversation. If you want to leave it open for others to find the conversation that's perfect to me :-)

**Comment by partnerinflight** [comment]
I believe closed issues can be found as well; I'd rather not keep issues open that we don't intend to address.
