### ISSUE TITLE
Behavior and handling of SSO dialog on MSAL in the sign-out process

### ISSUE THREAD

**Issue by ha-koichi** [AzureAD/microsoft-authentication-library-for-objc#1951]
Hello,

I am using SSO on iOS to enable Single Sign-On functionality on MSAL.
However, I am encountering the following two issues during the sign-out process:

**Issue:**

1. When the SSO dialog is displayed on sign-out process, tapping "Cancel" results in "Success" response, and not handling the cancellation (iOS is returning a Failure response).
2. Before the SSO dialog is shown on sign-out process, the token is deleted, and even if the SSO dialog is canceled by tapping "Cancel," the token still gets deleted.

**Question:**

1. Is it possible to return "Failure" response when tapping "Cancel" in the SSO dialog on sign-out process?
2. Could we adjust the sequence of the sign-out process to delete the token after displaying the SSO dialog on sign-out process?

**Comment by kaisong1990** [comment]
@ha-koichi Thanks for sharing, will take a look.

**Comment by kaisong1990** [comment]
`Is it possible to return "Failure" response when tapping "Cancel" in the SSO dialog on sign-out process?`

What you have observed indeed happens, and currently it is by design. The major gap the MSAL lib has is we don't know if user signed out from browser succeeded or not from in presented web session, and cancellation callback is the only information MSAL can capture at the time. In other words, no matter if user signed out or not from browser, if user clicks cancel button from navigation bar, MSAL ignores the cancellation error and return success in the completion block. So, clients don't know when to return failure after tapping cancel and treated as successful by default. Please refer to this logic:

https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/e23cb10d35ec3a8ce0c94f7e5a3a0a622e9d2873/IdentityCore/src/requests/MSIDOIDCSignoutRequest.m#L116

`Could we adjust the sequence of the sign-out process to delete the token after displaying the SSO dialog on sign-out process?`

Like above explanation, if MSAL does not know whether sign-out from browser is succeeded or not, reverting the logic would not help here.

For more info, please refer to this link:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1271

**Comment by ha-koichi** [comment]
@kaisong1990 Thank you very much.
I understand that the server does not return a callback and thereby it cannot be determined if it is "Success" or not.
Please let me confirm the following on the above.
Is it possible to return a "Cancel" (or "Failure") when an SSO dialog (SSO alert) is cancelled by the user, regardless of the server process?
My understanding is that iOS can return "Failure" when the SSO dialog is cancelled.
Because the SSO dialog is controlled by iOS.

Of course, I understand that the B2C token is still deleted and server side processing is still being performed when the dialog is cancelled. 
But I would like users to stop the sign-out process when the users cancels the SSO dialog.

**Comment by kaisong1990** [comment]
Hi @ha-koichi, your understanding is correct and currently system returns user cancellation error if clicks the Cancel button from the popover WebView, and we intentionally ignore this condition. Dismissing the sign-out WebView could mean two things:
1. Logout successfully
2. Logout failed

MSAL does not know and return successful as the initial local cache cleanup is good.

Could you clarify if  signout _from_browser is needed in the app? It is mostly designed for share_device, and if not needed, please set the value to No so no browser will be prompted.

If signout _from_browser is needed, I would suggest prompting a customized alert ahead to inform users what could happen and get confirmation if they'd still like to continue sign-out process before getting into MSAL code.

We do understand the gap and inconvenience and will let you know as soon as the improvement is set in our roadmap.

**Comment by ha-koichi** [comment]
@kaisong1990 Thank you for your reply to my comment.

> Could you clarify if signout _from_browser is needed in the app?

The signout _from_browser is necessary for me.
I want users to be used our services without login by SSO with browser, and I am thinking to realize it by Browser's cache.
Therefore, if I don't use signout _from_browser, the cache will not be deleted and only the same user will be able to login.


> It is mostly designed for share_device, and if not needed, please set the value to No so no browser will be prompted.

I do not know what share_device is.


> If signout _from_browser is needed, I would suggest prompting a customized alert ahead to inform users what could 
happen and get confirmation if they'd still like to continue sign-out process before getting into MSAL code.

Thank! I am also considering this method.




Please check the following source code for the issue of failure not returning.
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/6d13c11a4db5ddc30c45f06b12ea7c1edcef86c9/IdentityCore/src/requests/MSIDOIDCSignoutRequest.m#L115C70-L115C70

`if (error && ! ([error.domain isEqualToString:MSIDErrorDomain] && error.code == MSIDErrorUserCancel))`

The above is replaced by the following
`if (error && ! ([error.domain isEqualToString:MSIDErrorDomain]) && error.code == MSIDErrorUserCancel)`

With the current conditional logic, if the user cancels, the second half of the condition is always reversed to False and Success is always returned. Shouldn't the condition that the user cancels be modified so that it is not inverted?

`We do understand the gap and inconvenience and will let you know as soon as the improvement is set in our roadmap.`

Thank, We would like to set in the your roadmap. We also hope that the sign-out process will be modified so that the token is deleted after the SSO dialog is displayed.

**Comment by kaisong1990** [comment]
"With the current conditional logic, if the user cancels, the second half of the condition is always reversed to False and Success is always returned. Shouldn't the condition that the user cancels be modified so that it is not inverted?"

Hi @ha-koichi,  specifically on this comment, if we revert the logic, and user signed out successfully from browser and canceled the webview (As the browser cannot be dismissed automatically after user signed out successfully or failed), this would be a successful case, but the logic returns a failure because of user cancellation which is also an issue. 

In general, I think we should get the signout logically make sense in future with server-side support.

**Comment by kaisong1990** [comment]
"With the current conditional logic, if the user cancels, the second half of the condition is always reversed to False and Success is always returned. Shouldn't the condition that the user cancels be modified so that it is not inverted?"

Hi @ha-koichi,  specifically on this comment, if we revert the logic, and user signed out successfully from browser and canceled the webview (As the browser cannot be dismissed automatically after user signed out successfully or failed), this would be a successful case, but the logic returns a failure because of user cancellation which is also an issue. 

In general, I think we should get the signout logically make sense in future with server side support.

**Comment by ha-koichi** [comment]
Hi @kaisong1990 

I understand that you commented.
We will avoid this issue in another interim way.
Therefore, we will close this Issue.

We hope this issue will be set on your roadmap soon.

Thank you very much.
