### ISSUE TITLE
Sign out does not clear SSO token 

### ISSUE THREAD

**Issue by clairernovotny** [AzureAD/microsoft-authentication-library-for-objc#210]
Looking at the code, I don't see Sign Out being properly implemented. There is a way to remove the user tokens from the local cache, but it does not appear to invoke the system web view to hit the `end_session_endpoint` endpoint value. That may leave the cookie between the system and the device valid such that a subsequent authenticate call may not prompt for credentials.

Seems like the `end_session_endpoint` value should be read from the OIDC metadata and then invoked on a sign out?

**Comment by brandwe** [comment]
Hello @onovotny! You are correct that we only provide a way to clear the application state inside of your own app or family of apps with sharing a keychain. There is manual code you can write to do this, however. I share that below.

But first, I'd like to challenge you to think *why you want to sign your user out of the system web view.* There are some legitimate reasons why you would (LOB apps where you will want to remove the account - in particular when users share devices) but there is a lot of benefit to having the user's state persisted across the device, including the web browser.Just like someone would access your web app and probably never sign-out, the same is true for for the System web view. It'll help your users to have their accounts persisted the next time they need to sign-in. 

In addition, when a new app requests to sign in using MSAL, the user is always prompted to select their account from the System Webview (even if there is just one) so they are always in control of who gets their credentials. 

I bring this up because switching to a System Webview is sometimes a shift in thinking, but it's important to think deeply about the effect removing the user from the device has for both your apps and the users of other apps that might want to use these credentials.

As an example, if you remove a business account from the device, Office may not be thrilled a user has to sign in again :-) 

Also, the user is always in control of their sign-out at the device level. When you call this logout URI they are presented with confirmation if they want to sign out, they can choose not to signout of the system web view (and the device) and you may not know. The user is always in control of their credentials on a device.

With all that said, here is the code as an example:

You can clear the SSO state from the system web view calling the logout URI you get from the metadata. What is most important is that you make sure you grab a handle to the same system web view that is currently being used by the app, and append `post_logout_redirect_uri` with the return back to your app (this is usually your redirect URI). After that you can clear your own cache as usual as well to ensure a full signout. I have some code to help you below, written as if there was a button called "Signout" that attached to this event.

```objective-c
static NSString *const kLogoutURI =
@"https://login.microsoftonline.com/common/oauth2/v2.0/logout";
```
```objective-c
- (IBAction)signoutCurrentAccount:(nullable id)sender {
    NSURL *logoutURL = [[NSURL alloc]initWithString:kLogoutURI];
  //  NSDictionary *params = @{@"post_logout_redirect_uri":kRedirectURI};

    
    NSURLComponents *components = [[NSURLComponents alloc] initWithURL:logoutURL resolvingAgainstBaseURL:NO];
    NSURLQueryItem * newQueryItem = [[NSURLQueryItem alloc] initWithName:@"post_logout_redirect_uri" value:kRedirectURI];
    NSMutableArray * newQueryItems = [NSMutableArray arrayWithCapacity:[components.queryItems count] + 1];
    for (NSURLQueryItem * qi in components.queryItems) {
        if (![qi.name isEqual:newQueryItem.name]) {
            [newQueryItems addObject:qi];
        }
    }
    [newQueryItems addObject:newQueryItem];
    [components setQueryItems:newQueryItems];
    
    logoutURL = [components URL];

    
    if ([SFSafariViewController class] != nil) {
        SFSafariViewController *sfvc = [[SFSafariViewController alloc] initWithURL:logoutURL];
        [self presentViewController:sfvc animated:YES completion:nil];
    } else {
        [[UIApplication sharedApplication] openURL:logoutURL];
    }

```

Let me know if you have any feedback. I'd love to hear your thoughts!

**Comment by onovotny** [comment]
The scenario I'm thinking about is with B2C -- If I have a native app that uses the flows, there's no real way to sign out without this.... In the app, I click "sign out", and it'll clear the local tokens, but then Clicking "sign in" gives the appearance of auto-signing in. That's completely unexpected... unless the solution is to add `login_prompt=always` parameter? Even there, that could leave the user with a false sense of "logged out-ness" if they are suddenly logged in in their browser.

**Comment by brandwe** [comment]
@onovotny What you say is true. We've thought about this for our own IdP using MSAL (Microsoft), and after Preview, we plan to use language similar to Google does when they moved their apps to the System web view: "sign in to your account and the browser". You could take that approach, although we both know users don't always read content.

Depending on the ambition for a developer's B2C service - they may have a website that also uses the B2C identity and this gives the user a seamless experience across web browser and app, or you have multiple apps and you'd like SSO across those apps. The System Webview gives you that.

However, if you just want the user to sign out of both the app and the system webview, then you should certainly use `end_session_endpoint` in the system web view and remove the user's cookie (if they agree). If you do call the `end_session_endpoint` and the user declines to be signed out, they will be less surprised when they find they are still signed in to the browser if they use the app again.

**Comment by onovotny** [comment]
@brandwe can I ask why this is closed? Seems like it should stay open until MSAL implements this directly?

**Comment by brandwe** [comment]
Sure we can keep it open for tracking purposes if you'd like. We do have this work item in our internal work item list.

**Comment by mendesbarreto** [comment]
Hello guys,

Do you have a simple code in Swift for resolve this situation?

Thank you

**Comment by marksands** [comment]
Bumping this issue. This is really an unacceptable miss in the implementation of this library. If I manually sign out of an authentication session, I would 100% expect all of my tokens to be invalidated on the server. I would consider this a violation of a user's privacy to pretend they're signed out. This is also a major violation of the "principle of least surprise". Please fix.

**Comment by ismael9291** [comment]
For anyone still having issues with this. I ended up using 

- (void)acquireTokenForScopes:(nonnull NSArray<NSString *> *)scopes
                    loginHint:(nullable NSString *)loginHint
                   promptType:(MSALPromptType)promptType
         extraQueryParameters:(nullable NSDictionary <NSString *, NSString *> *)extraQueryParameters
              completionBlock:(nonnull MSALCompletionBlock)completionBlock;

with promptType .login to always ask for user's credentials at login. and to logout, i just use 

- (BOOL)removeAccount:(nonnull MSALAccount *)account
                error:(NSError * _Nullable __autoreleasing * _Nullable)error;

**Comment by marksands** [comment]
@ismael9291 That is not a secure solution. That does not clear the server side token, it only removes the cached access token from the keychain. If someone has a copy of that token, they can still use it to remain authenticated until the refresh token expiration date, which could be valid for a year.

**Comment by ismael9291** [comment]
@marksands I am also separately using the URL previously mentioned to logout from the server "https://login.microsoftonline.com/common/oauth2/v2.0/logout"

This isn't 100% because what if you don't have internet at that time, but since I don't expect this library to be updated any time soon and I really rely on it, I thought this was my only workaround.

**Comment by ismael9291** [comment]
Workaround failed because if another person signs in, the token received by MSAL is actually from the previous user.

**Comment by psahgal** [comment]
By the way, that issue @ismael9291 mentioned is another Github issue: #560.

**Comment by GithubAshishHere** [comment]
> ```objc
> NSURL *logoutURL = [[NSURL alloc]initWithString:kLogoutURI];
> 
>     
>     NSURLComponents *components = [[NSURLComponents alloc] initWithURL:logoutURL resolvingAgainstBaseURL:NO];
>     NSURLQueryItem * newQueryItem = [[NSURLQueryItem alloc] initWithName:@"post_logout_redirect_uri" value:kRedirectURI];
>     NSMutableArray * newQueryItems = [NSMutableArray arrayWithCapacity:[components.queryItems count] + 1];
>     for (NSURLQueryItem * qi in components.queryItems) {
>         if (![qi.name isEqual:newQueryItem.name]) {
>             [newQueryItems addObject:qi];
>         }
>     }
>     [newQueryItems addObject:newQueryItem];
>     [components setQueryItems:newQueryItems];
>     
>     logoutURL = [components URL];
> 
>     
>     if ([SFSafariViewController class] != nil) {
>         SFSafariViewController *sfvc = [[SFSafariViewController alloc] initWithURL:logoutURL];
>         [self presentViewController:sfvc animated:YES completion:nil];
>     } else {
>         [[UIApplication sharedApplication] openURL:logoutURL];
>     }
> ```

what will be the redirect URL in this?
can I log out with an open browser or web view?

**Comment by oldalton** [comment]
In the latest MSAL, you can now call [signout API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)signoutWithAccount:signoutParameters:completionBlock:), and if you set [signoutFromBrowser](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALSignoutParameters.html#/c:objc(cs)MSALSignoutParameters(py)signoutFromBrowser) to YES, this will also do the browser signout.
