### ISSUE TITLE
How can I handle browser clicks? Suppose, if I will have to handle a certain link how can I take control of webview in iOS?

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#223]
Suppose, if I will have to handle a certain link how can I take control of webview in iOS?

**Comment by RPangrle** [comment]
This is out of scope for a GitHub issue. MSAL uses a System Web View which by design you do not have control over from the context of the application. The application taking control over it is a security violation. If you're looking to automate it you should investigate a UIAutomation based solution like Appium.
