### ISSUE TITLE
“Server returned less scopes than requested”.

### ISSUE THREAD

**Issue by rbrayb** [AzureAD/microsoft-authentication-library-for-objc#393]
This is with Azure AD B2C.

This error occurs on version 0.2.0.

We then downgraded to 0.1.4 and the error no longer occurs.

The scopes that were requested were the clientID and offline_access.

With 0.2.0 we could successfully authenticate on B2C and the access token and refresh tokens were returned.

![image](https://user-images.githubusercontent.com/5341999/47885375-8f47a580-de99-11e8-8570-83dcffbf3da4.png)

![image](https://user-images.githubusercontent.com/5341999/47885425-e2b9f380-de99-11e8-989c-08cc0c934789.png)

![image](https://user-images.githubusercontent.com/5341999/47885462-0a10c080-de9a-11e8-9951-b6afd2bd5de0.png)

**Comment by oldalton** [comment]
It means that server didn't recognize some of the scopes you provided and therefore didn't return those in response. Please see more info here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/master/MSAL/src/public/MSALError.h#L92
However, it's a bit weird that MSAL complained about "offline_access". Let me check if it's a bug.

**Comment by oldalton** [comment]
Thanks, we'll work on improving our documentation.
I checked your scopes in the sample, and "offline_access" is a reserved scope. MSAL appends it to each request anyway, so please don't pass it to MSAL yourself.
Regarding "clientId" scope, MSAL had logic to remove clientId from passed scopes, because AAD doesn't support it. Therefore, MSAL silently removed the scope from the request and you would never get it back in response. I just submitted a PR to improve this logic to be more explicit [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/309). Instead of silently removing clientId scope, MSAL will now fail the acquireToken call for AAD with an explicit error message.
