### ISSUE TITLE
Scopes are case sentitive, MSAL objc is lowercasing scopes and should not be

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [AzureAD/microsoft-authentication-library-for-objc#395]
See https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/b7dc31c26ffc6ff4172dfcc85cdbae4dc3058b5c/MSAL/src/requests/MSALRequestParameters.m#L73

Reported by an internal customer:
https://stackoverflow.microsoft.com/questions/108249/msal-ios-scope-parameter-sent-to-login-microsoftonline-com-as-all-lowercase

MSAL for objc is sending the scope to login.microsoftonline.com as all lowercase. 
This causes issues of the AppIdURI for the api they are accessing has mixed casing. Therefore the API results in a 401 Access Denied due to audience validation.

MSAL for dotnet keeps the case sensitivity for the scopes. 

According to both the Open ID Connect spec and the OAuth 2 spec, scopes are intended to be case sensitive. 

https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
"Multiple scope values MAY be used by creating a space delimited, **case sensitive** list of ASCII scope values."

https://tools.ietf.org/html/rfc6749#section-3.3
"The value of the scope parameter is expressed as a list of space-delimited, **case-sensitive** strings.  The strings are defined by the authorization server.  If the value contains multiple space-delimited strings, their order does not matter, and each string adds an additional access range to the requested scope."

**Comment by oldalton** [comment]
Did the fix, but we should also keep in mind that AAD itself treats scopes as case insensitive. So, if you send a scope in a different case, AAD will return it back in a "corrected" case. So, it might be that customer will still experience issues even after the fix.

e.g. customer sends USER.read
MSAL now sends USER.read to AAD (previously sent user.read)
AAD returns User.Read in response and in access token
If customer now tries to verify that the access token has USER.read, it will still fail, because AAD corrected casing and returned User.Read

**Comment by oldalton** [comment]
Fixed. Closing the issue.
