### ISSUE TITLE
Requires user interaction every time token expiration

### ISSUE THREAD

**Issue by christophercarlsson** [AzureAD/microsoft-authentication-library-for-objc#449]
Hi,
I have an issue where the application requires me to user interact every time the token expires, im unable to refresh the token.

Im doing the following when acquiring the token for the first time
`
self.msalApplication.acquireToken(forScopes: scopes) { (result, error) in ...
`
where I save the access token, expiry time and the account.homeAccountId.identifier.

When the token has expired, I do the following
`
let account: MSALAccount = try self.msalApplication.account(forHomeAccountId: homeAccountId)
self.msalApplication.acquireTokenSilent(forScopes: scopes, account: account, completionBlock: { (result, error) in ... }
`

When I do this, error says the following
> Error Domain=MSALErrorDomain Code=-42100 "(null)" UserInfo={MSALErrorDescriptionKey=User interaction is required, MSALOAuthErrorKey=invalid_grant, MSALOAuthSubErrorKey=basic_action, NSUnderlyingError=0x282100660 {Error Domain=MSALErrorDomain Code=-42004 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.

When this happens, I do the first code bit again and save the new information. But I don't want my users to have to get the authentication screen every time.
We recently changed the scopes of the application (just one time, not multiple as the error would suggest), but the application is requesting tokens with the new scope.
What do I need to change?

Best regards

**Comment by danieldobalian** [comment]
This error is generated when the user needs to do multi-factor authentication which can be triggered for a few reasons. 

In particular,
1. There is a Conditional Access policy set by the tenant admin requiring the user to MFA each time they request a token for the scopes you're requesting. 
2. The token you're using to refresh the AT with doesn't request or have the MFA claim.  

More than likely, it's caused by the first reason. Are you able to check your tenants Conditional Access policies and see if this is the case? 

To elaborate more on the second possible case, it's possible your interactive request is requesting a different set of scopes and thus not triggering the MFA that's being prompted for in the error.  To verify if this is the case, can you share the scopes you're requesting in each request and if the user is performing MFA on the `acquireToken(...)` request?

**Comment by christophercarlsson** [comment]
@danieldobalian any news on this?

**Comment by oldalton** [comment]
Sorry for a late followup. Are you still seeing the issue?
