### ISSUE TITLE
iOS 13 failure

### ISSUE THREAD

**Issue by sameertotey** [AzureAD/microsoft-authentication-library-for-objc#698]
Running the iOS sample app on iOS 12.4 works fine.  However while running it on iOS 13.0 phones gives the following error:

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700}

This error is returned in the completion block of the call to:
```
- (void)acquireTokenWithParameters:(nonnull MSALInteractiveTokenParameters *)parameters
                   completionBlock:(nonnull MSALCompletionBlock)completionBlock;
```

I have the same issue using the sample app provided as well

**Comment by sameertotey** [comment]
I am also getting the following error on iOS 13.0 from another app:
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALInternalErrorCodeKey=-42008}

**Comment by sameertotey** [comment]
After updating the iOS phone to 13.1, I get the following error message:
TID=6901 MSAL 0.8.0 iOS 13.1 [2019-09-24 22:22:00 - 351C7BFB-026A-4429-BC19-C61B523EDFB9] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)

**Comment by sameertotey** [comment]
If I delete the Microsoft Authenticator App it does seem to work.

**Comment by oldalton** [comment]
Thanks for reporting this. I think there was an unnecessary check in the sample. Please download the latest sample and retry. Here's the change I've made: https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc/pull/57

**Comment by sameertotey** [comment]
Thank you for the quick response.

**Comment by AntonPieter** [comment]
Hi. I have the same problem. The AppDelegate changes are not enough, I think. Could it be that the library relies on UIApplication.SharedApplication.OpenUrl? Apple made API changes that are breaking. It only happens when the Authenticator App is installed.

**Comment by oldalton** [comment]
@AntonPieter, can you please show your AppDelegate or UISceneDelegate code? See a sample here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#swift-1

**Comment by AntonPieter** [comment]
@oldalton Thanks for your reply. This is inside my AppDelegate:
`extension AppDelegate {
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String)
    }
}`

**Comment by AntonPieter** [comment]
@oldalton I think the library tries to open the Authenticator app, if it is installed, but nothing happens. When I remove the Authenticator app, it will show the safariViewController (or wkWebView, whatever the webviewType is set to). Note, that I didn't add an account to the Authenticator app.

**Comment by oldalton** [comment]
Thanks for additional information. When you're saying that "nothing happens", is the Authenticator app shown? Is your app opened after that?

**Comment by AntonPieter** [comment]
The Authenticator app does not show. It will stay in our app.

**Comment by oldalton** [comment]
Thanks, can you please collect a verbose MSAL log as described here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=dotnet#logging-in-msal-for-ios-and-macos

**Comment by AntonPieter** [comment]
Sure:
`MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] (Default cache) Get app metadata entries with clientId 444e76f9-2a66-4002-8b7a-92891c2f11e9, environment (null)
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Trying to find keychain items...
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Keychain find status: -34018
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Failed to find keychain item (status: -34018)
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Failed to retrieve app metadata items with error code -34018, MSIDKeychainErrorDomain
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] (Default accessor) Get accounts.
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Trying to find keychain items...
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Keychain find status: -34018
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Failed to find keychain item (status: -34018)
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Trying to find keychain items...
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Keychain find status: -34018
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Failed to find keychain item (status: -34018)
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] (Default accessor) Failed refresh token lookup
Didn't find any accounts in cache: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)"
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] Requiring default broker type due to app being built with iOS 13 SDK
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Checking broker install state for version V2-broker-nonce
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Broker version V2-broker-nonce found installed on device
MSAL log: TID=5075605 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Beginning broker flow.
MSAL log: TID=5075879 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] No cached preferred_network for authority
MSAL log: TID=5075879 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Sending network request: (not-null), headers: (not-null)
MSAL log: TID=5075879 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Waiting on Authority Validation Queue
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18] session:didReceiveChallenge:completionHandler - nsurlauthenticationmethodservertrust. Host: login.microsoftonline.com. Previous challenge failure count: 0
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:18 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Received network response: (not-null), error (null)
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Parsed response: (not-null), error (null), error domain: (null), error code: 0
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Caching AAD Environements
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Resolved authority, validated: YES, error: 0
MSAL log: TID=5075869 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Broker flow finished.
MSAL log: TID=5075879 MSAL 1.0.6 iOS 13.3 [2020-01-20 12:24:19 - C1A17307-E857-4717-9920-0A288FD34055] [MSAL] Returned from Authority Validation Queue`

**Comment by oldalton** [comment]
@AntonPieter, please make sure you configured keychain sharing correctly, as described in step nr 3 here: https://github.com/AzureAD/microsoft-authentication-library-for-objc#adding-msal-to-your-project

**Comment by AntonPieter** [comment]
@oldalton I completely missed this in the docs. Thanks! It is working now.

**Comment by jagrutiJ** [comment]
Hello
@oldalton I am facing Sign out issue with MSAL pod 1.0.3.
When I try to add following funtion
  let signoutParameters = MSALSignoutParameters(webviewParameters: self.webViewParamaters!)

giving me error as Use of unresolved identifier 'MSALSignoutParameters'

I want to sign out from browser as well.

**Comment by ashishLanghe-iOS** [comment]
I'm unable to resolve this issue. Please help me.

I'm trying to implement this, still unable to get success.

Please let me know which branch I should try to implement? 

My System Configuration :

  - Mac OS    : macOS High Sierra
  - XCode Ver : Version 10.1 (10B61)

I'm getting following issues :
```
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03] Default app's access group: "Masked(not-null)".
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03] Using "Masked(not-null)" Team ID.
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03] Init MSIDKeychainTokenCache with keychainGroup: Masked(not-null)
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
    "User.Read"
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:Masked(null)
                                               promptType:MSALPromptTypePromptIfNecessary
                                     extraQueryParameters:(null)
                                                authority:(null)
                                              webviewType:MSALWebviewTypeDefault
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Checking broker install state for version V2-broker
2020-07-17 10:38:03.586934+0530 XYZ MSAL_App[58046:2641259] -canOpenURL: failed for URL: "msauthv2://broker" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03] Scheme msauthv2 for broker not present
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Beginning interactive flow.
TID=2641259 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
TID=2641341 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] No cached preferred_network for authority
TID=2641341 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:03 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Waiting on Authority Validation Queue
2020-07-17 10:38:04.082442+0530 XYZ MSAL_App[58046:2641334] TIC SSL Trust Error [1:0x600002076a00]: 3:0
2020-07-17 10:38:04.091317+0530 XYZ MSAL_App[58046:2641334] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9807)
2020-07-17 10:38:04.091652+0530 XYZ MSAL_App[58046:2641334] Task <D71F58E1-89B6-4C4D-AD1C-51F07303E19B>.<1> HTTP load failed (error code: -1202 [3:-9807])
2020-07-17 10:38:04.092249+0530 XYZ MSAL_App[58046:2641345] Task <D71F58E1-89B6-4C4D-AD1C-51F07303E19B>.<1> finished with error - code: -1202
TID=2641334 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:04 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Resolved authority, validated: NO, error: -1202
TID=2641334 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:04 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Interactive flow finished result (null), error: -1202 error domain: NSURLErrorDomain
TID=2641334 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:04 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] acquireToken returning with error: (NSURLErrorDomain, -1202) Masked(not-null)
TID=2641341 MSAL 1.0.0 iOS Sim 12.1 [2020-07-17 05:08:04 - C2508177-7B64-4BE9-9F95-98BE60F27A77] [MSAL] Returned from Authority Validation Queue
App error: Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “login.microsoftonline.com” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600002775170>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSErrorFailingURLKey=https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize, NSErrorFailingURLStringKey=https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f8f430ea000) s: stamp2.login.microsoftonline.com i: XYZ Primary Proxy SSL Interception Service>"
), NSErrorClientCertificateStateKey=0, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “login.microsoftonline.com” which could put your confidential information at risk., _kCFStreamErrorDomainKey=3, NSUnderlyingError=0x600001b03fc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9807, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600002775170>, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9807, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7f8f430ea000) s: stamp2.login.microsoftonline.com i: XYZ Primary Proxy SSL Interception Service>"
)}}, _kCFStreamErrorCodeKey=-9807}
2020-07-17 10:40:03.652983+0530 XYZ MSAL_App[58046:2641344] Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2020-07-17 10:40:03.653307+0530 XYZ MSAL_App[58046:2641344] Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
```
Apart from this, I'm trying to trust SSL pinning certificate...but still it gives me same issue.
```
//MARK: - Trust SSL Pinning
extension MSALViewController: URLSessionDelegate {
    
    func configureURLSession() {
        self.defaultSession = URLSession(configuration: URLSessionConfiguration.default, delegate: self, delegateQueue: nil)
    }
    
        func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Swift.Void) {
    
            if (challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust) {
                if let trust = challenge.protectionSpace.serverTrust,
                    let pem = Bundle.main.path(forResource: microsoftonlineCert, ofType: "cer"),
                    let data = NSData(contentsOfFile: pem),
                    let cert = SecCertificateCreateWithData(nil, data) {
                    let certs = [cert]
                    SecTrustSetAnchorCertificates(trust, certs as CFArray)
    
                    completionHandler(URLSession.AuthChallengeDisposition.useCredential, URLCredential(trust: trust))
                    return
                }
                else{
                    print("In Else Condition!")
                }
            }
            else{
                print("In Else Condition!")
            }
    
            // Pinning failed
            completionHandler(URLSession.AuthChallengeDisposition.cancelAuthenticationChallenge, nil)
        }
    
}
```

**Comment by xiaochuan4938** [comment]
@oldalton 
<img width="944" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/15375679/458ab28a-aa16-43a6-9baa-e03a9ef8d154">

**Comment by oldalton** [comment]
> @oldalton <img alt="image" width="944" src="https://user-images.githubusercontent.com/15375679/251759938-458ab28a-aa16-43a6-9baa-e03a9ef8d154.png">

@xiaochuan4938, both are correct. RedirectURI includes the "auth" part as the host, and the URL scheme has to only include scheme.

**Comment by xiaochuan4938** [comment]
> > @oldalton <img alt="image" width="944" src="https://user-images.githubusercontent.com/15375679/251759938-458ab28a-aa16-43a6-9baa-e03a9ef8d154.png">
> 
> @xiaochuan4938, both are correct. RedirectURI includes the "auth" part as the host, and the URL scheme has to only include scheme.

got it and thanks.

**Comment by Compu-Tek** [comment]
Can anybody help me to get pass this
[MSAL ERROR] Full error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700, MSALCorrelationIDKey=73CBC443-8292-44BF-B763-DB6F5996E5C8}

When logging in from my app, the broker opens up and I authenticate my self, select the account I wish to login with and I get sent correctly back to my app.
But I'm not getting the token from the broker (Microsoft authenticator)
