### ISSUE TITLE
Login Without using UIWebView? 

### ISSUE THREAD

**Issue by a-elnajjar** [AzureAD/microsoft-authentication-library-for-objc#745]
Could we use the authentication-library without using Popover UIWebView?

**Comment by oldalton** [comment]
This is not supported by MSAL. Do you have a specific scenario you're trying to accomplish?

**Comment by a-elnajjar** [comment]
We want to use our custom loginViewControlller and connect to Azure B2C using MSAL without the  Popover UIWebView.

**Comment by oldalton** [comment]
You can use resource owner password flow with Azure B2C to achieve that: https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-ropc#test-the-user-flow.

However, while it is supported on the service side, we don't recommend this flow for any native apps (outside of unit tests) and we don't support it in MSAL. The reason for it is security, SSO and conditional access.

SSO: User might already have an SSO cookie in the web browser, so user wouldn't need to type their credentials again. 
Conditional access: If there's MFA or other conditional access policy, you'll need to show WebView because user needs to perform interaction.
Security: This is covered well in the OAuth2 spec https://tools.ietf.org/html/rfc6749#section-10.7

```
Resource Owner Password Credentials

   The resource owner password credentials grant type is often used for
   legacy or migration reasons.  It reduces the overall risk of storing
   usernames and passwords by the client but does not eliminate the need
   to expose highly privileged credentials to the client.

   This grant type carries a higher risk than other grant types because
   it maintains the password anti-pattern this protocol seeks to avoid.
   The client could abuse the password, or the password could
   unintentionally be disclosed to an attacker (e.g., via log files or
   other records kept by the client).

   Additionally, because the resource owner does not have control over
   the authorization process (the resource owner's involvement ends when
   it hands over its credentials to the client), the client can obtain
   access tokens with a broader scope than desired by the resource
   owner.  The authorization server should consider the scope and
   lifetime of access tokens issued via this grant type.

   The authorization server and client SHOULD minimize use of this grant
   type and utilize other grant types whenever possible.
```

**Comment by a-elnajjar** [comment]
ok thanks
