### ISSUE TITLE
Bring back support for macOS 10.11

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#747]
macOS 10.11 was supported in v0.50. v0.7 then broke this for us and our apps started crashing. We were told it's fixed in v0.71 however I now see support for macOS 10.11 has been removed completed. 

We're now stuck on v0.5 and would like to upgrade to the latest release of MSAL. Please back port whatever change you had to make to support 10.12 or disable it for 10.11 users and make this library available. macOS 10.11 isn't that old and we've got a large chunk of our users using it on 10.11 (especially since businesses don't seem to upgrade to the latest macOS version for at least 2 years at times).

**Comment by guidedways** [comment]
I can also see there are some important fixes in the latest version of MSAL that we'd like to use, especially on Catalina. However we cannot abandon our 10.11 users simply because MSAL won't work. 

A library such as MSAL should aim at remaining generic enough such that it supports the least three years worth of macOS releases at least. It's not uncommon for app developers to try and support macOS 10.10 even. We'd have done that had it not been a major pain to support both `NSEffectiveView`s and their non-existence in the view hierarchy at runtime.

**Comment by guidedways** [comment]
I suspect the macOS 10.12 requirement listed on the main page is misleading and incorrect. The library itself seems to have no usage of unavailable APIs on macOS 10.11, however the only macOS 10.12 reliant code is in the test app:

`@property (weak) IBOutlet WKWebView *webView;`

Can this be 'fixed' so that on the test app continues to work without relying on `WKWebView` and the requirements updated to reflect that it should work on macOS 10.11?

**Comment by oldalton** [comment]
Hi. WKWebView is available on 10.10 and above (see in Apple docs: https://developer.apple.com/documentation/webkit/wkwebview?language=objc). Would you mind clarifying what needs to be fixed with this line?

`@property (weak) IBOutlet WKWebView *webView;`

Regarding what is declared as supported version, I've provided some more context on another thread: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/706

We're seeing less than 2.5% of users on macOS versions below 10.12. Note that supported macOS version indicates a version that we'll help resolving issues with. Older versions might still work, but we don't perform regular testing with these.
