### ISSUE TITLE
-5005 errors when logging in

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#753]
I'm not sure what to make of this - one of our users is able to connect to their work account just fine, but seeing this when they connect to a personal Office 365 account. Is that not going to work?

`Error Domain=MSALErrorDomain Code=-50005 "The operation couldn’t be completed. (MSALErrorDomain error -50005.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (MSALErrorDomain error -50005.)}`

**Comment by oldalton** [comment]
This means user cancelled interactive authentication. Could you please provide a correlationId or a specific error that your user is seeing? Thanks.

**Comment by guidedways** [comment]
@oldalton Can you tell me how to get the correlationID? I'm see this for instance:

2020-04-16 08:27:50 -2- MSAL: could not aquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALOAuthErrorKey=access_denied, MSALInternalErrorCodeKey=-42104} => {
    MSALInternalErrorCodeKey = "-42104";
    MSALOAuthErrorKey = "access_denied";
}
Error Domain=MSALErrorDomain Code=-50000 "Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALOAuthErrorKey=access_denied, MSALInternalErrorCodeKey=-42104}" UserInfo={NSLocalizedDescription=Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALOAuthErrorKey=access_denied, MSALInternalErrorCodeKey=-42104}}

**Comment by oldalton** [comment]
Correlation ID would be seen in MSAL logs: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc. Each log line is prefixed with the correlation ID.

However, I think we should also include correlation ID in error like you're showing. Filed an issue to track and fix: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/908

**Comment by guidedways** [comment]
That would be very helpful, since we frequently get complaints that MSAL isn't working for them, but connecting via a normal login / password and auto discovery does, so I'm not really sure what to say to such users. Those errors would help.

**Comment by brenmcnamara** [comment]
Quick note here that we ran into a similar issue when using MSAL in our application.
- We had a customer who was willing to go through the trouble of debugging with us
- Got a screen recording indicating the issues as well as the error payloads with Microsoft Authenticator
- Collected debug data, such as the correlation id and additional MSAL logs
- Followed up with Microsoft support to see if they could help us debug further.
- However, Microsoft Support indicated they would not proceed because the user's login failed prior to a successful authentication attempt, and we did not have permission to debug user data with them.
- At this point, we are trying to get a support number from Microsoft so we can pass that along to our customer, so they may debug this issue directly
