### ISSUE TITLE
"Different account was returned from the server" error is returned on request for password change

### ISSUE THREAD

**Issue by xZachi** [AzureAD/microsoft-authentication-library-for-objc#824]
1. Log in to the app using B2C signIn/signUp policy
2. Launch change password flow using dedicated policy (using MSALPublicClientApplication)

ER: Password is changed, MSALResult is returned, error is empty
AR: Password is changed, MSALResult is empty, error as below
Error:
`Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Different account was returned from the server, MSALCorrelationIDKey=03FF3E15-FB38-4540-8F04-7FFBF0E45E5C, MSALInternalErrorCodeKey=-42101, MSALInvalidResultKey=<MSALResult: 0x600001361b00>}`

System: iOS 13.3
MSAL Version: 1.0.2

**Comment by rohitnarula7176** [comment]
@xZachi We were able to reproduce this issue. The problem is here is that the object id of the account returned from the policy endpoint in B2C is of the form <object id>-<policy>
For instance , when you go to signIn/signUp policy, the object id of the account returned from server is <object id>-b2c_1_signin,

Now when you pass this account in the parameters of the subsequent acquireTokenWithParameters call to go to the password_reset policy, the object id of the account returned from server is 
<object id>-b2c_1_passwordreset . 

MSAL tries to match the returned account from password reset policy with the account passed and fails with error "Different account returned from server"

As a workaround, you can either not pass the account in the acquireTokenWithParameters api call or make sure that you pass the policy specific account for each call to the policy endpoint. You can implement the second choice using the snippet from one of our public samples below

```
 func getAccountByPolicy (withAccounts accounts: [MSALAccount], policy: String) throws -> MSALAccount? {
        
        for account in accounts {
            // This is a single account sample, so we only check the suffic part of the object id,
            // where object id is in the form of <object id>-<policy>.
            // For multi-account apps, the whole object id needs to be checked.
            if let homeAccountId = account.homeAccountId, let objectId = homeAccountId.objectId {
                if objectId.hasSuffix(policy.lowercased()) {
                    return account
                }
            }
        }
        return nil
    }
```

**Comment by kesanf** [comment]
I am not sure if this is production ready. This library looks bad. You have a lot of bugs on both iOS and Android

**Comment by rohitnarula7176** [comment]
@kesanf Can you please provide more details on why the above workaround did not work for you. Can you please share a code snippet that you are using for your flow so we can further investigate the issue you are facing.

**Comment by kesanf** [comment]
@rohitnarula7176 This is not even workaround. getAccountByPolicy is method that you need, not workaround.

**Comment by oldalton** [comment]
@kesanf, yes, getAccountByPolicy is additional code that you need to include in your application in order to retrieve correct account object for the policy you're trying to execute. Unfortunately, in the B2C world, each policy has a separate account associated with it due to protocol limitations.

Can you please provide a code snippet that you're using (in case that after applying additional code you're still experiencing same issue).

**Comment by oldalton** [comment]
Following up on this issue. Can you please provide us a code snippet that you're using in order to help investigate. Thanks.

**Comment by kesanf** [comment]
> @kesanf, yes, getAccountByPolicy is additional code that you need to include in your application in order to retrieve correct account object for the policy you're trying to execute. Unfortunately, in the B2C world, each policy has a separate account associated with it due to protocol limitations.
> 
> Can you please provide a code snippet that you're using (in case that after applying additional code you're still experiencing same issue).

Nope. I use exactly the same code.
