### ISSUE TITLE
Override decidePolicyForNavigationAction for customWebView

### ISSUE THREAD

**Issue by eltonjhony** [AzureAD/microsoft-authentication-library-for-objc#837]
Hi,

Is there a way to override ```decidePolicyForNavigationAction``` when using a customWebView? 

I tested here with my ```customWebView``` and the events are not intercepted. Does it require any additional step other than implementing ```WKNavigationDelegate```?

**Comment by antrix1989** [comment]
hi @eltonjhony, could you provide more details why do you need to override decidePolicyForNavigationAction?

**Comment by eltonjhony** [comment]
Hi @antrix1989 

We have a B2C journey here where we're opening in a ```customWebView```. In this journey there is a cancel button which calls a redirect URL for this cancel purpose. 

I want to override ```decidePolicyForNavigationAction``` to intercept the cancel redirect URL and call the appropriated action if the user taps this button. 

I don't know if there is another way to do it using ```acquireToken``` method. 

Is there a way to setup the lib with more than one redirect URL? Because, in the journey I'm talking about, I have two redirects, one for success and another one for cancel.

**Comment by eltonjhony** [comment]
Do you have any thoughts antrix1989 to help me? Let me know if you need more information.

**Comment by oldalton** [comment]
@eltonjhony, thanks for the clarification. Neither MSAL nor OAuth2 spec allow to provide multiple redirect_uri-s in the request. Do you have any reason why your cancellation flow cannot use the same redirect_uri as provided to MSAL? Please make sure that your cancel redirect follows OAuth2 format for error responses. 

In order to detect cancellation, you can check error information returned by MSAL and react to this condition in your app as needed.

**Comment by eltonjhony** [comment]
Thanks for the response @oldalton 

We're gonna use the error check to decide what to do in this case.
