### ISSUE TITLE
Broker Authentication iOS

### ISSUE THREAD

**Issue by bullsseye** [AzureAD/microsoft-authentication-library-for-objc#845]
After reading many documentation I could not find much clarity on how to enable broker authentication with MSAL. While going through ADAL to MSAL migration doc: _https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-objc-adal-msal_ , I found that I just need to do the following if my applications' redirectURI is already broker enabled:

`- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> `*)options
`
{ return [MSALPublicClientApplication handleMSALResponse:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}`

1. I could not find any configuration to tell the application that it needs to enable broker authentication. For example in iOS .net lib there is withBroker() param while initializing PublicClientApplication and in the ADAL library we used to do it with ADCredentialType. 

2. Do I need to do something special for broker authentication in iOS13.

**Comment by jasoncoolmax** [comment]
For your Q1, by default, MSAL Objective C will automatically call broker if broker is available and your app settings are right. If you want to turn off broker, you can set the following flag:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/configuration/MSALGlobalConfig.h#L74

For your Q2: 
Please kindly refer to the following two links for iOS 13 requirements :)
https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL
**https://github.com/AzureAD/microsoft-authentication-library-for-objc#objective-c-1**

**Comment by tysonkerridge** [comment]
@jasoncoolmax It seems that on iOS 13 there's no way to use the broker (assuming by broker it means the Microsoft Authenticator App) due to the `sourceApplication` options property always being `nil` as mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL. Perhaps the configuration documentation in the readme should indicate this more clearly, or at least include that you need to set `MSALGlobalConfig.brokerAvailability` to `MSALBrokeredAvailability.none` in iOS 13 seeing as MSAL tries to use the broker by default otherwise? Please let me know if there's something I'm missing.
