### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by richardtop** [AzureAD/microsoft-authentication-library-for-objc#846]
Build fails when trying to run examples provided with this repository.
Also, no instructions are available on how to build the sample apps.

**Comment by jasoncoolmax** [comment]
Hi @richardtop , are you using cocoapods to get the library or download it directly from Github? If you download it from Github, make sure you are downloading via the first two links (rather than the last two). Because the first two links contain all required submodules to run the project out of box. Check the following link as an example: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.0.7

If that still won't build, please share the error you see, such that I can further investigate. Thanks!

**Comment by oldalton** [comment]
@richardtop, can you please provide additional information? Thanks.

**Comment by richardtop** [comment]
Hi @jasoncoolmax  & @oldalton  thanks for your quick reply!
I'll do more testing this week and send you specific steps to reproduce.
So far, I've just cloned this repo and tried to run examples with no success.

**Comment by oldalton** [comment]
Thanks. Please make sure you execute this command after cloning the repository:

`git submodule update --init`

MSAL uses submodules, so you need to pull all dependencies.

**Comment by richardtop** [comment]
So far MSAL Test app is not compiling due to the following error:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/8013017/74931673-ca504e00-53e8-11ea-8379-2424fd264aec.png">
**Content and frame layout guides before iOS 11.0 [6]**

If you don't mind, I'll just bump the deployment target to 11.0 and submit a pull request.

**Comment by richardtop** [comment]
@oldalton thanks for your suggestion. Cloning git submodules helped me to resolve the issue.

**Comment by oldalton** [comment]
Closing the issue. Please reopen if needed.

**Comment by richardtop** [comment]
@oldalton it is still relevant, please take a look at the screenshot :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
