### ISSUE TITLE
Apple "ITMS-90338: Non-public API usage" issue

### ISSUE THREAD

**Issue by GiulioVinci** [AzureAD/microsoft-authentication-library-for-objc#856]
Apple provided the following issue after I submitted my app:

"ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/xxxxx.framework/xxxxx: initWithParentViewController:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed."

The method Apple addesses might be MSALWebviewParameters constructor: 
-initWithParentViewController: 

(My app supports iOS 12, iOS13)

**Comment by oldalton** [comment]
Thanks for reporting this. MSAL doesn't use any private APIs, but some of its own selectors match Apple's own APIs. We've heard about a similar App Store issue before, let me see how it got resolved. If it cannot get resolved without a library update, we can take the fix.

**Comment by oldalton** [comment]
@GiulioVinci, just to double check, are you using Intune MAM SDK in your app as well by any chance?

**Comment by GiulioVinci** [comment]
@oldalton Thanks for your quick reply. No I'm using MAM SDK. The Apple reject message is probably generated by one of their scripts.

**Comment by DrAma999** [comment]
Hello @oldalton have you any update on that issue?
I am a colleague of @GiulioVinci  and basically we have a 3 whole projects blocked for this reason, and business is pressuring us for a resolution. They are also asking, since we are paying for Active Directory if there is a sort of "premium" assistance.
Could you get back to us?
Thank you so much,
Andrea

**Comment by oldalton** [comment]
Sure, I followed up with our internal apps who have also run into this issue in the past.
They worked it around by adding a "dummy" initWithParentViewController: selector declaration into their app. Since we're not using any private APIs, this is just working around Apple's script bug.

On our side, we'll need to deprecate initWithParentViewController: initializer and replace it with something else. It will take some time to prepare a new release... If you can unblock yourself with the suggestion above in the meantime, that would be great. Thanks!

**Comment by oldalton** [comment]
Did you try the workaround? Please let us know if that worked. Thanks.

**Comment by DrAma999** [comment]
> Did you try the workaround? Please let us know if that worked. Thanks.

Hello Olga, I will try tomorrow. I was thinking to create a DummyViewController that implements this method, tomorrow I let you know.
`class DummyViewController: UIViewController {
    @objc(initWithParentViewController:)
    init(with parent: UIViewController) {
        super.init(nibName: nil, bundle: nil)
    }
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
`

**Comment by DrAma999** [comment]
Hello @oldalton , iTunes connect seems to have accepted our build. The workaround fixed the issue with the automatic Apple script.
In the meantime I really recommend to update the library and avoid this issue in the future.
Best,
Andrea

**Comment by oldalton** [comment]
Thanks for the confirmation. We'll certainly update the library. Since it's a public API, it will require a breaking change for all developers, which is a bit unfortunate. It will take some time to prepare and communicate a breaking change.

**Comment by oldalton** [comment]
This is fixed in MSAL 1.1.2: https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases/tag/1.1.2

Please give it a try. You'll need to update to new MSAL API: 

	`let webviewParameters = MSALWebviewParameters(authPresentationViewController: viewController)`

**Comment by oldalton** [comment]
Closing the issue as it has been resolved. Please reopen if still seeing this issue.
