### ISSUE TITLE
Question: incremental upgrade from 0.1.3 to 0.1.4

### ISSUE THREAD

**Issue by alokc83** [AzureAD/microsoft-authentication-library-for-objc#860]
Dear Team, 
My org had this library statically added code version 0.1.3 for very long. 
my first task is to get it updated. We are deciding to do an incremental update. 
The only change that I see code-wise is _users -> accounts_ 

To know more about the impact I got the 0.1.4 release and read the changelog. There is nothing much which points about "users" changing to "accounts". 
my question is if this is just a refactor from users to account and not logic is changed what is users/accounts would do.  

if you can guide me to proper documentation that can help me to understand this change. It would be great. 

Thanks, Bunch. 
Alok C

**Comment by oldalton** [comment]
Hi. Yes, I believe it was just users being renamed to accounts. However, 0.1.4 doesn't support latest iOS version and it's a preview version of the library. Since MSAL has already been announced as generally available starting at 1.0.0, I'd highly encourage you to update to the latest version of 1.0.7 which also supports iOS 13+ devices. Thanks.

**Comment by alokc83** [comment]
@oldalton Thanks a lot for the information. Due to lack of resource my plan is to make incremental updates each sprint. So functionality is not broken. I really do appreciate you answering my query. 
Much thanks.

**Comment by oldalton** [comment]
Thanks. The problem is that we won't be able to provide any fixes or support you if you find issues with < 1.x MSAL versions. There're also some known bugs in earlier versions and we therefore highly recommend you to switch to 1.x immediately.
