### ISSUE TITLE
getting error while signing in 

### ISSUE THREAD

**Issue by eljoJoseph** [AzureAD/microsoft-authentication-library-for-objc#917]
Printing description of error:
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS650051:+Using+application+'SnapSupport'+is+currently+not+supported+for+your+organization+ceino.com+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+ceino.com+before+the+application+SnapSupport+can+be+provisioned.
Trace+ID:+5b3251c2-426e-4529-b10d-493529ea0100
Correlation+ID:+a1e2c388-e12f-4530-a904-4da569078f88
Timestamp:+2020-04-22+15:03:56Z, MSALOAuthErrorKey=invalid_client, MSALInternalErrorCodeKey=-42003}
2020-04-22 20:34:42.335776+0530 SnapSupport[87686:6361950] error

**Comment by mipetriu** [comment]
@eljoJoseph This error seems to be due to a misconfiguration of the tenant. The following documentation may be helpful to you.

[https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-custom-domain](url)

[https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/domains-admin-takeover](url)

**Comment by oldalton** [comment]
Closing the issue. Feel free to reopen if you have additional questions.
