### ISSUE TITLE
What scope parameter to be used for "deviceid" additional claim to exclude azure conditional access policies ? 

### ISSUE THREAD

**Issue by smudireddy** [AzureAD/microsoft-authentication-library-for-objc#954]
Hi,
What scope should be used for "deviceid" additional claim in a interactive token fetch request to "register" the device to AAD where conditional policies applied to the current user.  Currently when we request that additional claim, Authenticator app  on iOS device authenticated the user but shown "Enroll Now" option due to the CA policy failure.  Why CA policies applied when Authenticator app made a request to register the device to AAD ?. The CA policies should not be enforced when "deviceid" claim present in the request. Is there any correction needed in scope parameter for "registration service" which will not fall into CA policy ?

**Comment by oldalton** [comment]
We don't recommend taking a dependency on deviceId claim or requesting it explicitly.
What you're seeing is likely caused by the "require compliant device" policies in your tenant which require device to be managed by Intune. You can read more about CA policies here: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices
