### ISSUE TITLE
ADAL (2.7.14) to MSAL (1.1.5) -> "accountForUsername" gives MSALAccount as nil

### ISSUE THREAD

**Issue by smudireddy** [AzureAD/microsoft-authentication-library-for-objc#988]
MSAL 1.1.3
ADAL 2.7.14
OS : iOS 13.5.1

User signed in with ADAL 2.7.14. While upgrading the App to newer version with MSAL 1.1.5,  [publicClintApp accountForUsername:UserID]  returned nil. user signed-in with ADAL using the upn value of the user's account.  

* ClientID and resource/scope were same pre and post upgrade. Working few times but most of the time result is nil.

Our old agent not persisted the "homeAccountID" of the account to which user signed-in with ADAL so we are trying to find out the existing account by MSAL "accountForUsername" API.  What went wrong in identifying the account ?

**Comment by oldalton** [comment]
Thanks for this question. Can you do a couple of tests to help us understand what went wrong?

1. Query all accounts and see if ADAL account is present.
2. Instead of using accountForUsername API, query accounts with enumeration parameters, specifying upn as username, and set returnOnlySignedInAccounts as false: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALAccountEnumerationParameters.html#/c:objc(cs)MSALAccountEnumerationParameters(py)returnOnlySignedInAccounts

If that doesn't work, please collect MSAL logs to take a closer look. Thanks.
